/**
 * Disclaimer Generator — pure logic.
 */

export interface ConfigOptions {
  name: string;
  url: string;
  email: string;
  jurisdiction: string;
  lastUpdated: string;
  customFields: Record<string, string>;
}

export function defaultOptions(): ConfigOptions {
  return {
    name: "Your Company Name",
    url: "https://example.com",
    email: "legal@example.com",
    jurisdiction: "United States",
    lastUpdated: new Date().toISOString().split("T")[0],
    customFields: {},
  };
}

export function generate(opts: ConfigOptions): string {
  const year = new Date().getFullYear();
  return `<!-- Disclaimer Generator generated by UnQTools -->
<section>
  <h1>Disclaimer Generator</h1>
  <p>Last updated: ${opts.lastUpdated}</p>

  <h2>1. Introduction</h2>
  <p>Welcome to ${opts.name} ("we", "us", or "our"). By accessing ${opts.url}, you agree to these terms.</p>

  <h2>2. Contact Information</h2>
  <p>If you have questions, contact us at ${opts.email}.</p>

  <h2>3. Governing Law</h2>
  <p>These terms are governed by the laws of ${opts.jurisdiction}.</p>

  <h2>4. Changes</h2>
  <p>We may update this document from time to time. Last updated: ${opts.lastUpdated}.</p>

  <p>© ${year} ${opts.name}. All rights reserved.</p>
</section>`;
}

export function generatePlainText(opts: ConfigOptions): string {
  // Strip HTML tags
  return generate(opts).replace(/<[^>]+>/g, "").replace(/\n\s*\n/g, "\n\n").trim();
}

export function validate(opts: ConfigOptions): string[] {
  const errors: string[] = [];
  if (!opts.name || opts.name.trim().length < 2) errors.push("Company name is required (min 2 chars)");
  if (!opts.url || !/^https?:\/\//.test(opts.url)) errors.push("Valid URL is required (must start with http:// or https://)");
  if (!opts.email || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(opts.email)) errors.push("Valid email is required");
  if (!opts.jurisdiction || opts.jurisdiction.trim().length < 2) errors.push("Jurisdiction is required");
  return errors;
}

export function getJurisdictions(): string[] {
  return [
    "United States", "United Kingdom", "European Union", "Canada", "Australia",
    "India", "Germany", "France", "Spain", "Italy", "Netherlands", "Brazil",
    "Japan", "Singapore", "United Arab Emirates", "South Africa",
  ];
}

export function exportConfig(opts: ConfigOptions): string {
  return JSON.stringify(opts, null, 2);
}

export function importConfig(json: string): ConfigOptions | null {
  try {
    const parsed = JSON.parse(json);
    if (!parsed.name || !parsed.url) return null;
    return { ...defaultOptions(), ...parsed };
  } catch {
    return null;
  }
}
