/**
 * .htaccess Rules Generator — pure logic.
 *
 * Builds Apache `.htaccess` directives for common scenarios:
 *   • Redirects (301 permanent / 302 temporary)
 *   • HTTP basic authentication (.htpasswd gate)
 *   • IP deny / allow lists
 *   • Security headers (CSP, X-Frame-Options, HSTS, etc.)
 *   • URL rewrite rules (force HTTPS, www ↔ non-www, pretty URLs)
 *
 * Each section is opt-in; the generator only emits requested blocks.
 */

export interface RedirectRule {
  from: string;
  to: string;
  permanent?: boolean; // 301 by default
}

export interface IpRule {
  ip: string; // CIDR or single IP
  action: "allow" | "deny";
}

export type SecurityHeaderFlag =
  | "csp"
  | "xFrameOptions"
  | "xContentTypeOptions"
  | "hsts"
  | "referrerPolicy"
  | "permissionsPolicy";

export type RewriteFlag =
  | "forceHttps"
  | "wwwToNonWww"
  | "nonWwwToWww"
  | "removeTrailingSlash"
  | "addTrailingSlash"
  | "hidePhpExt";

export interface HtaccessConfig {
  redirects?: RedirectRule[];
  auth?: { realm: string; htpasswdPath: string };
  ipRules?: IpRule[];
  securityHeaders?: SecurityHeaderFlag[];
  rewriteRules?: RewriteFlag[];
  /** Directory listing (default off). */
  directoryListing?: boolean;
  /** Default page when accessing a directory. */
  defaultPage?: string;
  /** Pretty URL rewrite (e.g. /post/123 → /post.php?id=123). */
  prettyUrls?: { pattern: string; target: string };
}

export interface HtaccessResult {
  content: string;
  sections: string[];
  config: HtaccessConfig;
  warnings: string[];
}

function escAttr(s: string): string {
  return s.replace(/"/g, '\\"');
}

function validateIp(ip: string): boolean {
  // simple IPv4 / CIDR check
  return /^(\d{1,3}\.){3}\d{1,3}(\/\d{1,2})?$/.test(ip);
}

export function generateHtaccess(config: HtaccessConfig): HtaccessResult | { error: string } {
  const warnings: string[] = [];
  const sections: string[] = [];
  const lines: string[] = ["# Generated by unqtools .htaccess rules generator", "# All paths are relative to your site root unless absolute.", ""];

  if (config.directoryListing !== undefined) {
    sections.push("directory-listing");
    lines.push("# Directory listing");
    lines.push(`Options ${config.directoryListing ? "+Indexes" : "-Indexes"}`);
    lines.push("");
  }

  if (config.defaultPage) {
    sections.push("default-page");
    lines.push("# Default page");
    lines.push(`DirectoryIndex ${config.defaultPage}`);
    lines.push("");
  }

  if (config.redirects && config.redirects.length > 0) {
    sections.push("redirects");
    lines.push("# Redirects");
    for (const r of config.redirects) {
      const code = r.permanent === false ? 302 : 301;
      lines.push(`Redirect ${code} ${escAttr(r.from)} ${escAttr(r.to)}`);
    }
    lines.push("");
  }

  if (config.auth) {
    sections.push("auth");
    if (!config.auth.htpasswdPath) {
      return { error: "Auth block requires an htpasswdPath." };
    }
    lines.push("# Basic authentication");
    lines.push("AuthType Basic");
    lines.push(`AuthName "${escAttr(config.auth.realm || "Restricted")}"`);
    lines.push(`AuthUserFile ${config.auth.htpasswdPath}`);
    lines.push("Require valid-user");
    lines.push("");
    if (!/\.htpasswd$/.test(config.auth.htpasswdPath)) {
      warnings.push("AuthUserFile path doesn't end in .htpasswd — verify the path.");
    }
  }

  if (config.ipRules && config.ipRules.length > 0) {
    sections.push("ip-rules");
    const invalid = config.ipRules.filter((r) => !validateIp(r.ip));
    for (const r of invalid) warnings.push(`IP rule "${r.ip}" does not look like a valid IPv4/CIDR.`);
    lines.push("# IP allow / deny");
    lines.push("Order Allow,Deny");
    const allows = config.ipRules.filter((r) => r.action === "allow");
    const denies = config.ipRules.filter((r) => r.action === "deny");
    for (const a of allows) lines.push(`Allow from ${a.ip}`);
    for (const d of denies) lines.push(`Deny from ${d.ip}`);
    if (denies.length === 0) lines.push("Allow from all");
    lines.push("");
  }

  if (config.securityHeaders && config.securityHeaders.length > 0) {
    sections.push("security-headers");
    lines.push("# Security headers");
    lines.push("<IfModule mod_headers.c>");
    for (const h of config.securityHeaders) {
      switch (h) {
        case "csp":
          lines.push('  Header set Content-Security-Policy "default-src \'self\'; script-src \'self\'; style-src \'self\' \'unsafe-inline\'"');
          break;
        case "xFrameOptions":
          lines.push('  Header set X-Frame-Options "SAMEORIGIN"');
          break;
        case "xContentTypeOptions":
          lines.push('  Header set X-Content-Type-Options "nosniff"');
          break;
        case "hsts":
          lines.push('  Header set Strict-Transport-Security "max-age=31536000; includeSubDomains"');
          break;
        case "referrerPolicy":
          lines.push('  Header set Referrer-Policy "strict-origin-when-cross-origin"');
          break;
        case "permissionsPolicy":
          lines.push('  Header set Permissions-Policy "geolocation=(), microphone=(), camera=()"');
          break;
      }
    }
    lines.push("</IfModule>");
    lines.push("");
  }

  if (config.rewriteRules && config.rewriteRules.length > 0) {
    sections.push("rewrite-rules");
    lines.push("# Rewrite rules");
    lines.push("<IfModule mod_rewrite.c>");
    lines.push("  RewriteEngine On");
    for (const r of config.rewriteRules) {
      switch (r) {
        case "forceHttps":
          lines.push("  RewriteCond %{HTTPS} off");
          lines.push("  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
          break;
        case "wwwToNonWww":
          lines.push("  RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]");
          lines.push("  RewriteRule ^ https://%1%{REQUEST_URI} [L,R=301]");
          break;
        case "nonWwwToWww":
          lines.push("  RewriteCond %{HTTP_HOST} !^www\\. [NC]");
          lines.push("  RewriteRule ^ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
          break;
        case "removeTrailingSlash":
          lines.push("  RewriteRule ^(.*)/$ /$1 [L,R=301]");
          break;
        case "addTrailingSlash":
          lines.push("  RewriteCond %{REQUEST_FILENAME} !-f");
          lines.push("  RewriteRule ^(.*[^/])$ /$1/ [L,R=301]");
          break;
        case "hidePhpExt":
          lines.push("  RewriteCond %{REQUEST_FILENAME}.php -f");
          lines.push("  RewriteRule ^([^.]+)$ $1.php [L]");
          break;
      }
    }
    lines.push("</IfModule>");
    lines.push("");
  }

  if (config.prettyUrls) {
    sections.push("pretty-urls");
    lines.push("# Pretty URLs");
    lines.push("<IfModule mod_rewrite.c>");
    lines.push("  RewriteEngine On");
    lines.push("  RewriteCond %{REQUEST_FILENAME} !-f");
    lines.push("  RewriteCond %{REQUEST_FILENAME} !-d");
    lines.push(`  RewriteRule ${escAttr(config.prettyUrls.pattern)} ${escAttr(config.prettyUrls.target)} [L,QSA]`);
    lines.push("</IfModule>");
    lines.push("");
    if (!config.prettyUrls.pattern.startsWith("^")) warnings.push("Pretty URL pattern does not start with ^ — it may match more URLs than expected.");
  }

  return { content: lines.join("\n").trim() + "\n", sections, config, warnings };
}

/** Generate a sample htpasswd entry (using bcrypt-style placeholder; not secure — use Apache's htpasswd CLI for real hashing). */
export function sampleHtpasswdLine(username: string): string {
  return `${username}:$apr1$placeholder$ Replace with output of: htpasswd -nbB ${username} password`;
}

/** Describe a security header flag in plain English. */
export function describeHeader(flag: SecurityHeaderFlag): string {
  const map: Record<SecurityHeaderFlag, string> = {
    csp: "Content-Security-Policy — restricts which sources may load scripts, styles, etc.",
    xFrameOptions: "X-Frame-Options — prevents your site from being framed (clickjacking).",
    xContentTypeOptions: "X-Content-Type-Options — stops browsers from MIME-sniffing.",
    hsts: "Strict-Transport-Security — forces HTTPS for the given max-age.",
    referrerPolicy: "Referrer-Policy — controls how much referrer info is leaked.",
    permissionsPolicy: "Permissions-Policy — disables powerful APIs (camera, mic, etc.).",
  };
  return map[flag];
}
