import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        unq: {
          bg: "var(--unq-bg)",
          surface: "var(--unq-surface)",
          "surface-elevated": "var(--unq-surface-elevated)",
          "surface-hover": "var(--unq-surface-hover)",
          border: "var(--unq-border)",
          "border-strong": "var(--unq-border-strong)",
          text: "var(--unq-text)",
          "text-muted": "var(--unq-text-muted)",
          "text-subtle": "var(--unq-text-subtle)",
          accent: "var(--unq-accent)",
          "accent-hover": "var(--unq-accent-hover)",
          "accent-subtle": "var(--unq-accent-subtle)",
          "accent-contrast": "var(--unq-accent-contrast)",
          ring: "var(--unq-ring)",
          success: "var(--unq-success)",
          "success-subtle": "var(--unq-success-subtle)",
          warning: "var(--unq-warning)",
          "warning-subtle": "var(--unq-warning-subtle)",
          danger: "var(--unq-danger)",
          "danger-subtle": "var(--unq-danger-subtle)",
        },
      },
      fontFamily: {
        sans: [
          "Inter Variable",
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
      borderRadius: {
        sm: "var(--unq-radius-sm)",
        DEFAULT: "var(--unq-radius)",
        lg: "var(--unq-radius-lg)",
        xl: "var(--unq-radius-xl)",
        "2xl": "var(--unq-radius-xl)",
        full: "var(--unq-radius-full)",
      },
      boxShadow: {
        xs: "var(--unq-shadow-xs)",
        sm: "var(--unq-shadow-sm)",
        md: "var(--unq-shadow-md)",
        lg: "var(--unq-shadow-lg)",
        xl: "var(--unq-shadow-xl)",
        glow: "var(--unq-shadow-glow)",
      },
      fontSize: {
        xs: ["var(--unq-text-xs)", { lineHeight: "1.4" }],
        sm: ["var(--unq-text-sm)", { lineHeight: "1.45" }],
        base: ["var(--unq-text-base)", { lineHeight: "1.55" }],
        lg: ["var(--unq-text-lg)", { lineHeight: "1.5" }],
        xl: ["var(--unq-text-xl)", { lineHeight: "1.4" }],
        "2xl": ["var(--unq-text-2xl)", { lineHeight: "1.3" }],
        "3xl": ["var(--unq-text-3xl)", { lineHeight: "1.2" }],
        "4xl": ["var(--unq-text-4xl)", { lineHeight: "1.1" }],
        "5xl": ["var(--unq-text-5xl)", { lineHeight: "1.05" }],
      },
      spacing: {
        1: "var(--unq-space-1)",
        2: "var(--unq-space-2)",
        3: "var(--unq-space-3)",
        4: "var(--unq-space-4)",
        5: "var(--unq-space-5)",
        6: "var(--unq-space-6)",
        8: "var(--unq-space-8)",
        10: "var(--unq-space-10)",
        12: "var(--unq-space-12)",
        16: "var(--unq-space-16)",
        20: "var(--unq-space-20)",
      },
      transitionTimingFunction: {
        spring: "var(--unq-ease-spring)",
        out: "var(--unq-ease-out)",
        "in-out": "var(--unq-ease-in-out)",
      },
      transitionDuration: {
        fast: "var(--unq-duration-fast)",
        DEFAULT: "var(--unq-duration-normal)",
        slow: "var(--unq-duration-slow)",
      },
      maxWidth: {
        shell: "1200px",
        content: "768px",
      },
      containers: {
        xs: "320px",
        sm: "480px",
        md: "768px",
        lg: "1024px",
      },
    },
  },
  plugins: [],
};

export default config;
