/**
 * Redirect & htaccess Generator — pure logic.
 *
 * Pure functions only — no DOM, no network.
 */

export type RedirectType = "301" | "302" | "307" | "308";
export type DirectiveStyle = "RewriteRule" | "Redirect";

export interface RedirectEntry {
  from: string;
  to: string;
}

export interface RedirectOptions {
  type: RedirectType;
  style: DirectiveStyle;
  useRegex: boolean;
}

export interface CommonRedirectOptions {
  domain: string;
  wwwToNonWww: boolean;
  nonWwwToWww: boolean;
  httpToHttps: boolean;
  enforceTrailingSlash: boolean;
  stripTrailingSlash: boolean;
  stripQueryString: boolean;
}

export const HTACCESS_HEADER = `# Generated by UnQTools Redirect & htaccess Generator
RewriteEngine On
`;

/** Parse bulk input: "from -> to" or "from, to" or "from to" (space-separated). */
export function parseBulk(input: string): RedirectEntry[] {
  if (!input) return [];
  const out: RedirectEntry[] = [];
  for (const line of input.split(/\n+/)) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    let parts: string[] = [];
    if (trimmed.includes("->")) {
      parts = trimmed.split("->").map((s) => s.trim());
    } else if (trimmed.includes(",")) {
      parts = trimmed.split(",").map((s) => s.trim());
    } else if (trimmed.includes("=>")) {
      parts = trimmed.split("=>").map((s) => s.trim());
    } else {
      // Space-separated: take first token as from, rest as to
      const m = trimmed.match(/^(\S+)\s+(.+)$/);
      if (m) parts = [m[1], m[2]];
    }
    if (parts.length < 2 || !parts[0] || !parts[1]) continue;
    out.push({ from: parts[0], to: parts[1] });
  }
  return out;
}

/** Validate a URL/path. */
export function isValidUrlOrPath(url: string): boolean {
  if (!url) return false;
  // Allow absolute URLs
  if (/^https?:\/\//i.test(url)) {
    try {
      const u = new URL(url);
      return u.protocol === "http:" || u.protocol === "https:";
    } catch {
      return false;
    }
  }
  // Allow relative paths starting with /
  if (url.startsWith("/")) return true;
  // Allow regex patterns
  if (/^[\^$.\[\]()+*?\\a-zA-Z0-9_/-]+$/.test(url)) return true;
  return false;
}

/** HTML-escape (used for safe display in pre tags). */
export function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Build a single Redirect directive line. */
export function buildRedirectDirective(entry: RedirectEntry, type: RedirectType): string {
  return `Redirect ${type} ${entry.from} ${entry.to}`;
}

/** Build a single RewriteRule line. */
export function buildRewriteRule(entry: RedirectEntry, type: RedirectType, useRegex: boolean): string {
  const from = useRegex ? entry.from : `^${escapeRegex(entry.from)}$`;
  const flag = type === "301" ? "R=301,L" : type === "302" ? "R=302,L" : type === "307" ? "R=307,L" : "R=308,L";
  return `RewriteRule ${from} ${entry.to} [${flag}]`;
}

/** Escape a literal path for use in a regex. */
export function escapeRegex(input: string): string {
  return input.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Build full redirect rules block from bulk entries. */
export function buildRedirectRules(
  entries: RedirectEntry[],
  options: RedirectOptions,
): string {
  const lines: string[] = [HTACCESS_HEADER];
  if (options.style === "RewriteRule") {
    lines.push("RewriteEngine On");
    lines.push("");
    for (const e of entries) {
      if (!isValidUrlOrPath(e.from) || !isValidUrlOrPath(e.to)) continue;
      lines.push(buildRewriteRule(e, options.type, options.useRegex));
    }
  } else {
    for (const e of entries) {
      if (!isValidUrlOrPath(e.from) || !isValidUrlOrPath(e.to)) continue;
      lines.push(buildRedirectDirective(e, options.type));
    }
  }
  return lines.join("\n");
}

/** Build www → non-www rule. */
export function buildWwwToNonWww(domain: string): string {
  const d = domain.replace(/^https?:\/\//, "").replace(/\/+$/, "").trim();
  if (!d) return "";
  return [
    "RewriteCond %{HTTP_HOST} ^www\\." + escapeRegex(d) + " [NC]",
    `RewriteRule ^(.*)$ https://${d}/$1 [R=301,L]`,
  ].join("\n");
}

/** Build non-www → www rule. */
export function buildNonWwwToWww(domain: string): string {
  const d = domain.replace(/^https?:\/\//, "").replace(/\/+$/, "").trim();
  if (!d) return "";
  return [
    `RewriteCond %{HTTP_HOST} ^${escapeRegex(d)}$ [NC]`,
    `RewriteRule ^(.*)$ https://www.${d}/$1 [R=301,L]`,
  ].join("\n");
}

/** Build HTTP → HTTPS rule. */
export function buildHttpToHttps(): string {
  return [
    "RewriteCond %{HTTPS} off",
    "RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]",
  ].join("\n");
}

/** Build trailing slash enforcement rule. */
export function buildEnforceTrailingSlash(): string {
  return [
    "RewriteCond %{REQUEST_URI} /+[^\\.]+$",
    "RewriteRule ^(.+[^/])$ %{REQUEST_URI}/ [R=301,L]",
  ].join("\n");
}

/** Build strip trailing slash rule. */
export function buildStripTrailingSlash(): string {
  return [
    "RewriteCond %{REQUEST_FILENAME} !-d",
    "RewriteRule ^(.*)/$ /$1 [R=301,L]",
  ].join("\n");
}

/** Build strip query string rule. */
export function buildStripQueryString(): string {
  return [
    "RewriteCond %{QUERY_STRING} .+",
    "RewriteRule ^(.*)$ /$1? [R=301,L]",
  ].join("\n");
}

/** Build the common-redirects block. */
export function buildCommonRedirects(opts: CommonRedirectOptions): string {
  const lines: string[] = [HTACCESS_HEADER];
  if (opts.httpToHttps) {
    lines.push("# Force HTTPS");
    lines.push(buildHttpToHttps());
    lines.push("");
  }
  if (opts.wwwToNonWww) {
    lines.push("# www → non-www");
    lines.push(buildWwwToNonWww(opts.domain));
    lines.push("");
  }
  if (opts.nonWwwToWww) {
    lines.push("# non-www → www");
    lines.push(buildNonWwwToWww(opts.domain));
    lines.push("");
  }
  if (opts.enforceTrailingSlash) {
    lines.push("# Enforce trailing slash");
    lines.push(buildEnforceTrailingSlash());
    lines.push("");
  }
  if (opts.stripTrailingSlash) {
    lines.push("# Strip trailing slash");
    lines.push(buildStripTrailingSlash());
    lines.push("");
  }
  if (opts.stripQueryString) {
    lines.push("# Strip query string");
    lines.push(buildStripQueryString());
    lines.push("");
  }
  return lines.join("\n").trim();
}

/** Build the complete .htaccess file combining common + bulk. */
export function buildHtaccess(
  bulk: RedirectEntry[],
  redirectOpts: RedirectOptions,
  commonOpts: CommonRedirectOptions,
): string {
  const common = buildCommonRedirects(commonOpts);
  const bulkRules = buildRedirectRules(bulk, redirectOpts);
  // Combine, removing duplicate "RewriteEngine On" lines
  const combined = `${common}\n\n# Per-page redirects\n${bulkRules.replace(HTACCESS_HEADER, "")}`;
  return combined.trim() + "\n";
}

// ---- History (localStorage) ----

const HISTORY_KEY = "unqtools:redirect-htaccess-generator:history";
const HISTORY_MAX = 20;

export interface HistoryEntry {
  ts: number;
  ruleCount: number;
  type: RedirectType;
  style: DirectiveStyle;
}

export function loadHistory(): HistoryEntry[] {
  if (typeof localStorage === "undefined") return [];
  try {
    const raw = localStorage.getItem(HISTORY_KEY);
    if (!raw) return [];
    const arr = JSON.parse(raw) as HistoryEntry[];
    if (!Array.isArray(arr)) return [];
    return arr.slice(0, HISTORY_MAX);
  } catch {
    return [];
  }
}

export function saveHistory(entry: HistoryEntry): HistoryEntry[] {
  const next = [entry, ...loadHistory()].slice(0, HISTORY_MAX);
  if (typeof localStorage !== "undefined") {
    try {
      localStorage.setItem(HISTORY_KEY, JSON.stringify(next));
    } catch {
      // ignore
    }
  }
  return next;
}

export function clearHistory(): void {
  if (typeof localStorage === "undefined") return;
  try {
    localStorage.removeItem(HISTORY_KEY);
  } catch {
    // ignore
  }
}

// ---- Shareable URL ----

export function buildShareUrl(input: {
  bulk: string;
  redirectOpts: RedirectOptions;
  commonOpts: CommonRedirectOptions;
}): string {
  const params = new URLSearchParams();
  if (input.bulk) params.set("bulk", input.bulk);
  params.set("type", input.redirectOpts.type);
  params.set("style", input.redirectOpts.style);
  params.set("useRegex", input.redirectOpts.useRegex ? "1" : "0");
  if (input.commonOpts.domain) params.set("domain", input.commonOpts.domain);
  if (input.commonOpts.wwwToNonWww) params.set("wwwToNonWww", "1");
  if (input.commonOpts.nonWwwToWww) params.set("nonWwwToWww", "1");
  if (input.commonOpts.httpToHttps) params.set("httpToHttps", "1");
  if (input.commonOpts.enforceTrailingSlash) params.set("enforceTrailingSlash", "1");
  if (input.commonOpts.stripTrailingSlash) params.set("stripTrailingSlash", "1");
  if (input.commonOpts.stripQueryString) params.set("stripQueryString", "1");
  if (typeof window === "undefined") return `?${params.toString()}`;
  return `${window.location.origin}${window.location.pathname}#${params.toString()}`;
}

export function parseShareUrl(hash: string): {
  bulk: string;
  redirectOpts: RedirectOptions;
  commonOpts: CommonRedirectOptions;
} {
  const clean = hash.startsWith("#") ? hash.slice(1) : hash;
  const defaultCommon: CommonRedirectOptions = {
    domain: "",
    wwwToNonWww: false,
    nonWwwToWww: false,
    httpToHttps: false,
    enforceTrailingSlash: false,
    stripTrailingSlash: false,
    stripQueryString: false,
  };
  if (!clean) {
    return {
      bulk: "",
      redirectOpts: { type: "301", style: "RewriteRule", useRegex: false },
      commonOpts: defaultCommon,
    };
  }
  const params = new URLSearchParams(clean);
  const type = params.get("type");
  const style = params.get("style");
  return {
    bulk: params.get("bulk") ?? "",
    redirectOpts: {
      type: type === "302" || type === "307" || type === "308" ? type : "301",
      style: style === "Redirect" ? "Redirect" : "RewriteRule",
      useRegex: params.get("useRegex") === "1",
    },
    commonOpts: {
      domain: params.get("domain") ?? "",
      wwwToNonWww: params.get("wwwToNonWww") === "1",
      nonWwwToWww: params.get("nonWwwToWww") === "1",
      httpToHttps: params.get("httpToHttps") === "1",
      enforceTrailingSlash: params.get("enforceTrailingSlash") === "1",
      stripTrailingSlash: params.get("stripTrailingSlash") === "1",
      stripQueryString: params.get("stripQueryString") === "1",
    },
  };
}
