/**
 * Apache .htaccess Generator — generates common htaccess rules.
 */
export interface HtaccessOptions {
  redirectRules: { from: string; to: string; type: "301" | "302" }[];
  forceHttps: boolean;
  forceWww: boolean;
  removeWww: boolean;
  blockIps: string[];
  customErrorPages: { code: string; path: string }[];
  enableGzip: boolean;
  enableCors: boolean;
  corsOrigin: string;
  cacheControl: { type: string; maxAge: number }[];
  preventHotlinking: boolean;
  blockBots: boolean;
  disableDirectoryListing: boolean;
  phpVersion: string;
}

export const DEFAULTS: HtaccessOptions = {
  redirectRules: [], forceHttps: false, forceWww: false, removeWww: false,
  blockIps: [], customErrorPages: [], enableGzip: true, enableCors: false,
  corsOrigin: "*", cacheControl: [], preventHotlinking: false, blockBots: false,
  disableDirectoryListing: true, phpVersion: "",
};

export function generateHtaccess(opts: Partial<HtaccessOptions>): string {
  const o = { ...DEFAULTS, ...opts };
  const lines: string[] = ["# Generated by UnQTools .htaccess Generator", ""];

  if (o.disableDirectoryListing) {
    lines.push("# Disable directory listing", "Options -Indexes", "");
  }
  if (o.forceHttps) {
    lines.push("# Force HTTPS", "RewriteEngine On",
      "RewriteCond %{HTTPS} off", "RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]", "");
  }
  if (o.forceWww) {
    lines.push("# Force WWW", "RewriteEngine On",
      "RewriteCond %{HTTP_HOST} !^www\\. [NC]", "RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [L,R=301]", "");
  }
  if (o.removeWww) {
    lines.push("# Remove WWW", "RewriteEngine On",
      "RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]", "RewriteRule ^(.*)$ https://%1/$1 [L,R=301]", "");
  }
  for (const r of o.redirectRules) {
    lines.push(`# Redirect ${r.type}`, `Redirect ${r.type} ${r.from} ${r.to}`, "");
  }
  if (o.blockIps.length > 0) {
    lines.push("# Block IPs");
    for (const ip of o.blockIps) lines.push(`Require not ip ${ip}`);
    lines.push("");
  }
  if (o.enableGzip) {
    lines.push("# Enable GZIP compression",
      "<IfModule mod_deflate.c>", "  AddOutputFilterByType DEFLATE text/html text/plain text/css application/javascript application/json text/xml",
      "</IfModule>", "");
  }
  if (o.enableCors) {
    lines.push("# CORS headers", `<IfModule mod_headers.c>`,
      `  Header set Access-Control-Allow-Origin "${o.corsOrigin}"`,
      `  Header set Access-Control-Allow-Methods "GET, POST, OPTIONS"`,
      `  Header set Access-Control-Allow-Headers "Content-Type, Authorization"`,
      `</IfModule>`, "");
  }
  for (const c of o.cacheControl) {
    lines.push(`# Cache: ${c.type}`,
      `<FilesMatch "\\.(?:${c.type})$">`,
      `  <IfModule mod_expires.c>`,
      `    ExpiresActive On`,
      `    ExpiresByType ${c.type} "access plus ${c.maxAge} seconds"`,
      `  </IfModule>`, `</IfModule>`, "");
  }
  for (const e of o.customErrorPages) {
    lines.push(`ErrorDocument ${e.code} ${e.path}`);
  }
  if (o.preventHotlinking) {
    lines.push("", "# Prevent hotlinking", "RewriteEngine On",
      "RewriteCond %{HTTP_REFERER} !^$",
      "RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?yourdomain\\.com [NC]",
      "RewriteRule \\.(jpe?g|png|gif|webp|svg)$ - [F,NC,L]", "");
  }
  if (o.blockBots) {
    lines.push("# Block known bad bots", "RewriteEngine On",
      "RewriteCond %{HTTP_USER_AGENT} (badbot|spam-bot|scraper) [NC]",
      "RewriteRule ^ - [F,L]", "");
  }
  if (o.phpVersion) {
    lines.push(`# PHP version`, `AddHandler application/x-httpd-php${o.phpVersion} .php`, "");
  }
  lines.push("# End of generated .htaccess");
  return lines.join("\n");
}

export function validateHtaccess(content: string): { valid: boolean; warnings: string[] } {
  const warnings: string[] = [];
  const hasRewriteEngine = (content.match(/RewriteEngine On/g) || []).length;
  if (hasRewriteEngine > 3) warnings.push("Multiple RewriteEngine On directives — consider consolidating.");
  if (content.includes("RedirectMatch") && content.includes("Redirect ")) warnings.push("Mixing Redirect and RedirectMatch can cause conflicts.");
  if (!content.includes("RewriteEngine") && !content.includes("Redirect")) warnings.push("No redirect rules found.");
  return { valid: warnings.length === 0, warnings };
}
