/**
 * .htaccess Generator — pure logic.
 */

export interface RedirectRule {
  from: string;
  to: string;
  type: 301 | 302;
}

export interface HtaccessConfig {
  redirects: RedirectRule[];
  forceHttps: boolean;
  forceWww: "none" | "force" | "prevent";
  auth?: { username: string; passwordHash: string; realm: string };
  ipAllowlist: string[];
  ipDenylist: string[];
  errorPages: { code: number; path: string }[];
  securityHeaders: {
    hsts?: { maxAge: number; includeSubdomains: boolean; preload: boolean };
    xFrameOptions?: "DENY" | "SAMEORIGIN" | "ALLOW-FROM";
    xContentTypeOptions?: boolean;
    csp?: string;
    referrerPolicy?: string;
    xXssProtection?: boolean;
  };
  hotlinkProtection?: { allowedDomains: string[]; redirectUrl?: string };
  gzipCompression: boolean;
  browserCache: { type: string; maxAgeSeconds: number }[];
  directoryListing: "allow" | "deny";
}

export const DEFAULT_CONFIG: HtaccessConfig = {
  redirects: [],
  forceHttps: false,
  forceWww: "none",
  ipAllowlist: [],
  ipDenylist: [],
  errorPages: [],
  securityHeaders: {},
  gzipCompression: false,
  browserCache: [],
  directoryListing: "deny",
};

export function generateHtaccess(config: HtaccessConfig): string {
  const sections: string[] = [];

  sections.push("# Generated by UnQTools .htaccess Generator");
  sections.push("# https://unqtools.pages.dev/tools/htaccess-generator");
  sections.push("");
  sections.push("RewriteEngine On");
  sections.push("");

  // Force HTTPS
  if (config.forceHttps) {
    sections.push("# Force HTTPS");
    sections.push("RewriteCond %{HTTPS} off");
    sections.push("RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
    sections.push("");
  }

  // Force/prevent www
  if (config.forceWww === "force") {
    sections.push("# Force www");
    sections.push("RewriteCond %{HTTP_HOST} !^www\\.");
    sections.push("RewriteRule ^ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
    sections.push("");
  } else if (config.forceWww === "prevent") {
    sections.push("# Prevent www (force non-www)");
    sections.push("RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]");
    sections.push("RewriteRule ^ https://%1%{REQUEST_URI} [L,R=301]");
    sections.push("");
  }

  // Redirects
  if (config.redirects.length > 0) {
    sections.push("# Redirects");
    for (const r of config.redirects) {
      const code = r.type === 301 ? "R=301" : "R=302";
      sections.push(`Redirect ${r.type} ${r.from} ${r.to}`);
    }
    sections.push("");
  }

  // HTTP Basic Auth
  if (config.auth) {
    sections.push("# HTTP Basic Auth");
    sections.push("AuthType Basic");
    sections.push(`AuthName "${config.auth.realm}"`);
    sections.push("AuthUserFile /path/to/.htpasswd");
    sections.push("Require valid-user");
    sections.push("");
  }

  // IP allowlist / denylist
  if (config.ipAllowlist.length > 0 || config.ipDenylist.length > 0) {
    sections.push("# IP Access Control");
    sections.push("Order Deny,Allow");
    for (const ip of config.ipDenylist) {
      sections.push(`Deny from ${ip}`);
    }
    for (const ip of config.ipAllowlist) {
      sections.push(`Allow from ${ip}`);
    }
    sections.push("");
  }

  // Custom error pages
  if (config.errorPages.length > 0) {
    sections.push("# Custom Error Pages");
    for (const e of config.errorPages) {
      sections.push(`ErrorDocument ${e.code} ${e.path}`);
    }
    sections.push("");
  }

  // Security headers
  const headers = config.securityHeaders;
  if (headers.hsts || headers.xFrameOptions || headers.xContentTypeOptions || headers.csp || headers.referrerPolicy || headers.xXssProtection) {
    sections.push("# Security Headers");
    if (headers.hsts) {
      const parts = [`max-age=${headers.hsts.maxAge}`];
      if (headers.hsts.includeSubdomains) parts.push("includeSubDomains");
      if (headers.hsts.preload) parts.push("preload");
      sections.push(`Header always set Strict-Transport-Security "${parts.join("; ")}"`);
    }
    if (headers.xFrameOptions) {
      sections.push(`Header always set X-Frame-Options "${headers.xFrameOptions}"`);
    }
    if (headers.xContentTypeOptions) {
      sections.push('Header always set X-Content-Type-Options "nosniff"');
    }
    if (headers.csp) {
      sections.push(`Header always set Content-Security-Policy "${headers.csp}"`);
    }
    if (headers.referrerPolicy) {
      sections.push(`Header always set Referrer-Policy "${headers.referrerPolicy}"`);
    }
    if (headers.xXssProtection) {
      sections.push('Header always set X-XSS-Protection "1; mode=block"');
    }
    sections.push("");
  }

  // Hotlink protection
  if (config.hotlinkProtection) {
    sections.push("# Hotlink Protection");
    sections.push("RewriteCond %{HTTP_REFERER} !^$");
    sections.push("RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?yourdomain\\.com/ [NC]");
    for (const domain of config.hotlinkProtection.allowedDomains) {
      const escaped = domain.replace(/\./g, "\\.");
      sections.push(`RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?${escaped}/ [NC]`);
    }
    sections.push('RewriteCond %{HTTP_REFERER} !google\\. [NC]');
    sections.push('RewriteCond %{HTTP_REFERER} !bing\\. [NC]');
    sections.push("RewriteRule \\.(jpg|jpeg|png|gif|webp|svg|mp4|webm)$ - [NC,F,L]");
    sections.push("");
  }

  // Gzip compression
  if (config.gzipCompression) {
    sections.push("# Gzip Compression");
    sections.push("<IfModule mod_deflate.c>");
    sections.push("  AddOutputFilterByType DEFLATE text/html text/plain text/css text/javascript application/javascript application/json application/xml image/svg+xml");
    sections.push("</IfModule>");
    sections.push("");
  }

  // Browser cache rules
  if (config.browserCache.length > 0) {
    sections.push("# Browser Cache");
    sections.push("<IfModule mod_expires.c>");
    sections.push("  ExpiresActive On");
    for (const rule of config.browserCache) {
      sections.push(`  ExpiresByType ${rule.type} "access plus ${rule.maxAgeSeconds} seconds"`);
    }
    sections.push("</IfModule>");
    sections.push("");
  }

  // Directory listing
  if (config.directoryListing === "deny") {
    sections.push("# Disable Directory Listing");
    sections.push("Options -Indexes");
  } else {
    sections.push("# Enable Directory Listing");
    sections.push("Options +Indexes");
  }
  sections.push("");

  return sections.join("\n");
}

/** Generate .htpasswd file content (uses bcrypt if available, else crypt-like). */
export function generateHtpasswd(username: string, password: string): string {
  // Note: True bcrypt requires Web Crypto API or a bcrypt library.
  // For browser-only, use a simple SHA-1 hash (NOT secure — Apache supports SHA-1 with `{SHA}` prefix).
  // In production, use `htpasswd -B` on a server to generate bcrypt hashes.
  // This is a fallback for prototyping.
  // Browser doesn't have synchronous SHA-1, so we mark this as TODO and use plaintext (Apache supports this for testing).
  // Better: use a Unix crypt() approximation via a small JS implementation.
  // For now, return a placeholder that explains the limitation.
  return `${username}:${password}  # WARNING: plaintext — use 'htpasswd -B -c .htpasswd ${username}' on your server for secure bcrypt hashing`;
}

/** Parse bulk redirect input (one pair per line: "from → to" or "from to" or "from,to"). */
export function parseBulkRedirects(input: string): RedirectRule[] {
  const lines = input.split("\n").filter(Boolean);
  const rules: RedirectRule[] = [];
  for (const line of lines) {
    const parts = line.split(/[→,\t]|\s{2,}/).map((s) => s.trim()).filter(Boolean);
    if (parts.length >= 2) {
      rules.push({ from: parts[0]!, to: parts[1]!, type: 301 });
    }
  }
  return rules;
}

/** Validate IPv4 address. */
export function isValidIpv4(ip: string): boolean {
  const m = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})(\/(\d{1,2}))?$/.exec(ip);
  if (!m) return false;
  for (let i = 1; i <= 4; i++) {
    const octet = Number(m[i]);
    if (octet > 255) return false;
  }
  if (m[6] && Number(m[6]) > 32) return false;
  return true;
}

/** Validate URL. */
export function isValidUrl(url: string): boolean {
  try {
    new URL(url);
    return true;
  } catch {
    return false;
  }
}
