/**
 * .htaccess Generator — unit tests.
 */
import { describe, it, expect } from "vitest";
import { generateHtaccess, generateHtpasswd, parseBulkRedirects, isValidIpv4, isValidUrl, DEFAULT_CONFIG, type HtaccessConfig } from "./logic";

describe("generateHtaccess — basic", () => {
  it("generates a header comment", () => {
    const out = generateHtaccess(DEFAULT_CONFIG);
    expect(out).toContain("# Generated by UnQTools");
    expect(out).toContain("RewriteEngine On");
  });
  it("disables directory listing by default", () => {
    const out = generateHtaccess(DEFAULT_CONFIG);
    expect(out).toContain("Options -Indexes");
  });
});

describe("generateHtaccess — force HTTPS", () => {
  it("includes HTTPS rule when enabled", () => {
    const out = generateHtaccess({ ...DEFAULT_CONFIG, forceHttps: true });
    expect(out).toContain("RewriteCond %{HTTPS} off");
    expect(out).toContain("R=301");
  });
  it("omits HTTPS rule when disabled", () => {
    const out = generateHtaccess(DEFAULT_CONFIG);
    expect(out).not.toContain("RewriteCond %{HTTPS} off");
  });
});

describe("generateHtaccess — www force/prevent", () => {
  it("includes force-www rule", () => {
    const out = generateHtaccess({ ...DEFAULT_CONFIG, forceWww: "force" });
    expect(out).toContain("!^www\\.");
  });
  it("includes prevent-www rule", () => {
    const out = generateHtaccess({ ...DEFAULT_CONFIG, forceWww: "prevent" });
    expect(out).toContain("^www\\.(.+)$");
  });
  it("omits www rules when 'none'", () => {
    const out = generateHtaccess({ ...DEFAULT_CONFIG, forceWww: "none" });
    expect(out).not.toContain("www\\.");
  });
});

describe("generateHtaccess — redirects", () => {
  it("generates 301 redirects", () => {
    const out = generateHtaccess({
      ...DEFAULT_CONFIG,
      redirects: [{ from: "/old", to: "/new", type: 301 }],
    });
    expect(out).toContain("Redirect 301 /old /new");
  });
  it("generates 302 redirects", () => {
    const out = generateHtaccess({
      ...DEFAULT_CONFIG,
      redirects: [{ from: "/old", to: "/new", type: 302 }],
    });
    expect(out).toContain("Redirect 302 /old /new");
  });
});

describe("generateHtaccess — auth", () => {
  it("includes auth rules when configured", () => {
    const out = generateHtaccess({
      ...DEFAULT_CONFIG,
      auth: { username: "admin", passwordHash: "$2y$10$hash", realm: "Restricted" },
    });
    expect(out).toContain("AuthType Basic");
    expect(out).toContain('AuthName "Restricted"');
    expect(out).toContain("Require valid-user");
  });
});

describe("generateHtaccess — IP access", () => {
  it("includes allow/deny rules", () => {
    const out = generateHtaccess({
      ...DEFAULT_CONFIG,
      ipAllowlist: ["192.168.1.1"],
      ipDenylist: ["10.0.0.1"],
    });
    expect(out).toContain("Deny from 10.0.0.1");
    expect(out).toContain("Allow from 192.168.1.1");
  });
});

describe("generateHtaccess — error pages", () => {
  it("generates ErrorDocument directives", () => {
    const out = generateHtaccess({
      ...DEFAULT_CONFIG,
      errorPages: [
        { code: 404, path: "/404.html" },
        { code: 500, path: "/500.html" },
      ],
    });
    expect(out).toContain("ErrorDocument 404 /404.html");
    expect(out).toContain("ErrorDocument 500 /500.html");
  });
});

describe("generateHtaccess — security headers", () => {
  it("generates HSTS header", () => {
    const out = generateHtaccess({
      ...DEFAULT_CONFIG,
      securityHeaders: { hsts: { maxAge: 31536000, includeSubdomains: true, preload: true } },
    });
    expect(out).toContain("Strict-Transport-Security");
    expect(out).toContain("max-age=31536000");
    expect(out).toContain("includeSubDomains");
    expect(out).toContain("preload");
  });
  it("generates CSP header", () => {
    const out = generateHtaccess({
      ...DEFAULT_CONFIG,
      securityHeaders: { csp: "default-src 'self'" },
    });
    expect(out).toContain("Content-Security-Policy");
    expect(out).toContain("default-src 'self'");
  });
  it("generates X-Frame-Options", () => {
    const out = generateHtaccess({
      ...DEFAULT_CONFIG,
      securityHeaders: { xFrameOptions: "DENY" },
    });
    expect(out).toContain("X-Frame-Options");
    expect(out).toContain("DENY");
  });
});

describe("generateHtaccess — hotlink protection", () => {
  it("includes hotlink rules", () => {
    const out = generateHtaccess({
      ...DEFAULT_CONFIG,
      hotlinkProtection: { allowedDomains: ["example.com"] },
    });
    expect(out).toContain("RewriteCond %{HTTP_REFERER}");
    expect(out).toContain("(jpg|jpeg|png|gif|webp|svg|mp4|webm)");
  });
});

describe("generateHtaccess — gzip", () => {
  it("includes gzip rules", () => {
    const out = generateHtaccess({ ...DEFAULT_CONFIG, gzipCompression: true });
    expect(out).toContain("mod_deflate.c");
    expect(out).toContain("AddOutputFilterByType");
  });
});

describe("generateHtaccess — browser cache", () => {
  it("includes cache rules", () => {
    const out = generateHtaccess({
      ...DEFAULT_CONFIG,
      browserCache: [{ type: "image/jpeg", maxAgeSeconds: 86400 }],
    });
    expect(out).toContain("mod_expires.c");
    expect(out).toContain("ExpiresByType image/jpeg");
    expect(out).toContain("access plus 86400 seconds");
  });
});

describe("generateHtpasswd", () => {
  it("returns username:password format", () => {
    const out = generateHtpasswd("admin", "secret");
    expect(out).toContain("admin:");
    expect(out).toContain("secret");
  });
  it("includes warning about plaintext", () => {
    const out = generateHtpasswd("admin", "secret");
    expect(out).toContain("WARNING");
  });
});

describe("parseBulkRedirects", () => {
  it("parses arrow-separated pairs", () => {
    const r = parseBulkRedirects("/old → /new");
    expect(r.length).toBe(1);
    expect(r[0]).toEqual({ from: "/old", to: "/new", type: 301 });
  });
  it("parses comma-separated pairs", () => {
    const r = parseBulkRedirects("/old,/new");
    expect(r[0]).toEqual({ from: "/old", to: "/new", type: 301 });
  });
  it("parses multiple lines", () => {
    const r = parseBulkRedirects("/a → /b\n/c → /d");
    expect(r.length).toBe(2);
  });
  it("skips empty lines", () => {
    expect(parseBulkRedirects("/a → /b\n\n\n/c → /d").length).toBe(2);
  });
});

describe("isValidIpv4", () => {
  it("validates simple IP", () => {
    expect(isValidIpv4("192.168.1.1")).toBe(true);
  });
  it("validates IP with CIDR", () => {
    expect(isValidIpv4("192.168.1.0/24")).toBe(true);
  });
  it("rejects octet > 255", () => {
    expect(isValidIpv4("192.168.1.300")).toBe(false);
  });
  it("rejects CIDR > 32", () => {
    expect(isValidIpv4("192.168.1.0/40")).toBe(false);
  });
  it("rejects malformed input", () => {
    expect(isValidIpv4("not-an-ip")).toBe(false);
  });
});

describe("isValidUrl", () => {
  it("validates http URL", () => {
    expect(isValidUrl("http://example.com")).toBe(true);
  });
  it("validates https URL", () => {
    expect(isValidUrl("https://example.com/path")).toBe(true);
  });
  it("rejects plain text", () => {
    expect(isValidUrl("not a url")).toBe(false);
  });
});
