/**
 * AI robots.txt Custom Rule Builder — pure logic.
 *
 * Build a valid, tested robots.txt from plain-language intent or a visual rule
 * builder. Per-user-agent allow/disallow, crawl-delay, sitemap references, and
 * modern AI-crawler control (GPTBot, Google-Extended, CCBot, etc.).
 *
 * Implements the Robots Exclusion Protocol (RFC 9309) for the inline tester:
 * longest-rule-wins, wildcards (*), end-of-URL anchors ($), and Allow > Disallow
 * tie-breaking.
 *
 * Pure functions only — no DOM, no network. The optional LLM call (BYO API
 * key) lives in ui.tsx because it touches the network.
 */

// ---------- Types ----------

export type RuleType = "allow" | "disallow";

export interface Rule {
  id: string;
  userAgent: string;            // e.g. "GPTBot", "*", "" (treated as "*")
  type: RuleType;
  path: string;                 // e.g. "/", "/admin", "/private/*", "/api/*?ref=$"
}

export interface CrawlDelayRule {
  id: string;
  userAgent: string;
  delay: number;                // seconds
}

export interface RobotsTxtOptions {
  rules: Rule[];
  crawlDelays: CrawlDelayRule[];
  sitemaps: string[];
  headerComments: string[];
  blockAllAiCrawlers: boolean;
}

export interface RiskWarning {
  level: "ok" | "warn" | "danger";
  message: string;
  directive?: string;
}

export interface DirectiveExplanation {
  directive: string;
  value: string;
  explanation: string;
}

export interface GeneratedRobots {
  options: RobotsTxtOptions;
  text: string;
  warnings: RiskWarning[];
  explanations: DirectiveExplanation[];
}

export interface TestResult {
  url: string;
  userAgent: string;
  allowed: boolean;
  matchedRule?: Rule;
  matchedGroup: string;          // the user-agent group that decided
  reason: string;
}

export interface ParseResult {
  options: RobotsTxtOptions;
  warnings: RiskWarning[];
  unknownDirectives: string[];
}

export interface HistoryEntry {
  ts: number;
  ruleCount: number;
  sitemapCount: number;
  aiCrawlerBlock: boolean;
  hasCrawlDelay: boolean;
  preview: string;              // first ~80 chars
}

export interface ShareState {
  options: Partial<RobotsTxtOptions>;
}

export interface LlmPrompt {
  system: string;
  user: string;
}

// ---------- Constants ----------

export const HISTORY_KEY = "unqtools:ai-robots-txt-builder:history";
export const HISTORY_MAX = 20;

export const DEFAULT_OPTIONS: RobotsTxtOptions = {
  rules: [],
  crawlDelays: [],
  sitemaps: [],
  headerComments: [
    "Generated by UnQTools AI robots.txt Custom Rule Builder",
    "See https://www.rfc-editor.org/rfc/rfc9309.txt for the spec",
  ],
  blockAllAiCrawlers: false,
};

/** AI-crawler user-agent presets — the modern reason to use this tool. */
export interface AiCrawlerPreset {
  userAgent: string;
  vendor: string;
  purpose: string;
  defaultBlock: boolean;
}

export const AI_CRAWLER_PRESETS: AiCrawlerPreset[] = [
  { userAgent: "GPTBot",           vendor: "OpenAI",        purpose: "ChatGPT / GPT training & retrieval",      defaultBlock: true },
  { userAgent: "ChatGPT-User",     vendor: "OpenAI",        purpose: "Live ChatGPT user-initiated fetches",     defaultBlock: false },
  { userAgent: "OAI-SearchBot",    vendor: "OpenAI",        purpose: "SearchGPT search indexing",               defaultBlock: false },
  { userAgent: "Google-Extended",  vendor: "Google",        purpose: "Gemini AI training",                      defaultBlock: true },
  { userAgent: "CCBot",            vendor: "Common Crawl",  purpose: "Open dataset that feeds many AI models",  defaultBlock: true },
  { userAgent: "PerplexityBot",    vendor: "Perplexity",    purpose: "Perplexity answer engine retrieval",      defaultBlock: true },
  { userAgent: "ClaudeBot",        vendor: "Anthropic",     purpose: "Claude training & retrieval",             defaultBlock: true },
  { userAgent: "Claude-Web",       vendor: "Anthropic",     purpose: "Claude live user-initiated fetches",      defaultBlock: false },
  { userAgent: "Bytespider",       vendor: "ByteDance",     purpose: "TikTok / Douyin AI training",             defaultBlock: true },
  { userAgent: "FacebookBot",      vendor: "Meta",          purpose: "Meta AI retrieval",                       defaultBlock: false },
  { userAgent: "Applebot-Extended",vendor: "Apple",         purpose: "Apple Intelligence AI training",          defaultBlock: true },
  { userAgent: "ImagesiftBot",     vendor: "Imagesift",     purpose: "Image retrieval for AI training",         defaultBlock: true },
  { userAgent: "Diffbot",          vendor: "Diffbot",       purpose: "Automatic knowledge-graph construction",  defaultBlock: true },
  { userAgent: "Amazonbot",        vendor: "Amazon",        purpose: "Amazon AI training & Alexa",              defaultBlock: false },
];

/** Common non-AI crawler presets. */
export const SEARCH_CRAWLER_PRESETS: { userAgent: string; vendor: string }[] = [
  { userAgent: "Googlebot",  vendor: "Google" },
  { userAgent: "Bingbot",    vendor: "Microsoft" },
  { userAgent: "DuckDuckBot",vendor: "DuckDuckGo" },
  { userAgent: "Slurp",      vendor: "Yahoo" },
  { userAgent: "Baiduspider",vendor: "Baidu" },
  { userAgent: "YandexBot",  vendor: "Yandex" },
  { userAgent: "Applebot",   vendor: "Apple" },
];

export const SAMPLE_URL_PRESETS: string[] = [
  "https://example.com/",
  "https://example.com/admin",
  "https://example.com/admin/users",
  "https://example.com/blog/hello-world",
  "https://example.com/api/v1/data",
  "https://example.com/private/file.pdf",
];

// ---------- Helpers ----------

/** Generate a short unique id. */
export function genId(): string {
  return `r_${Math.random().toString(36).slice(2, 9)}_${Date.now().toString(36)}`;
}

/** Normalize a user-agent string: trim, lowercase comparison key, default "*" for empty. */
export function normalizeAgent(ua: string): string {
  const t = (ua || "").trim();
  return t === "" ? "*" : t;
}

/** Validate a path: must start with "/" or be "" (allow-all). No spaces. */
export function validatePath(path: string): { ok: boolean; reason?: string } {
  if (path === "") return { ok: true }; // empty path = allow-all
  if (!path.startsWith("/")) return { ok: false, reason: "Path must start with '/'" };
  if (/\s/.test(path)) return { ok: false, reason: "Path must not contain whitespace" };
  if (/[<>{}|\\^]/.test(path)) return { ok: false, reason: "Path contains forbidden characters" };
  // $ only allowed at end
  if (path.includes("$") && !path.endsWith("$")) {
    return { ok: false, reason: "'$' anchor only allowed at end of path" };
  }
  return { ok: true };
}

/** Validate a sitemap URL: must be absolute http(s) URL. */
export function validateSitemap(url: string): { ok: boolean; reason?: string } {
  if (!url) return { ok: false, reason: "Sitemap URL required" };
  if (!/^https?:\/\//i.test(url)) return { ok: false, reason: "Sitemap must be an absolute http(s) URL" };
  try {
    // eslint-disable-next-line no-new
    new URL(url);
    return { ok: true };
  } catch {
    return { ok: false, reason: "Invalid URL" };
  }
}

/** Validate a user-agent token: letters, digits, hyphens, underscores only. */
export function validateAgent(ua: string): { ok: boolean; reason?: string } {
  if (ua === "*" || ua === "") return { ok: true };
  if (!/^[A-Za-z0-9._+-]+$/.test(ua)) {
    return { ok: false, reason: "User-agent may only contain letters, digits, '.', '_', '+', '-'" };
  }
  return { ok: true };
}

/** Validate a URL for the tester. Returns the pathname + search (path portion). */
export function extractPathFromUrl(url: string): { ok: boolean; path?: string; reason?: string } {
  if (!url) return { ok: false, reason: "URL required" };
  let u: URL;
  try {
    u = new URL(url);
  } catch {
    // Maybe they pasted just a path
    if (url.startsWith("/")) return { ok: true, path: url };
    return { ok: false, reason: "Invalid URL — must be absolute (https://...)" };
  }
  return { ok: true, path: u.pathname + u.search };
}

// ---------- Path pattern matching (RFC 9309 §2.2.2) ----------

/**
 * Compile a robots.txt path pattern to a RegExp.
 * - `*` matches any sequence of characters
 * - `$` at end matches end-of-string
 * - Other chars are literal
 */
export function compilePattern(pattern: string): RegExp {
  if (pattern === "") {
    // Empty pattern in a Disallow means "allow everything".
    return new RegExp(""); // matches everything
  }
  let re = "^";
  for (let i = 0; i < pattern.length; i++) {
    const ch = pattern[i];
    if (ch === "*") {
      re += ".*";
    } else if (ch === "$" && i === pattern.length - 1) {
      re += "$";
    } else {
      // Escape regex special chars
      re += ch.replace(/[.+?^${}()|[\]\\]/g, "\\$&");
    }
  }
  return new RegExp(re);
}

/**
 * Match a path against a pattern. Returns the length of the matched portion
 * (per RFC 9309: longest match wins). Returns 0 if no match.
 */
export function matchPath(pattern: string, path: string): number {
  if (pattern === "") return 0; // empty pattern doesn't match for length purposes
  // Special case: "/" matches everything (it's the root)
  // But we still need to compute the longest match.

  // Build a regex that captures the longest prefix the pattern can match.
  // RFC 9309 says: "the most specific match found MUST be used. The most specific match is the longest
  // one that matches the path."
  // The "length" of a match is the number of characters of the path that the pattern consumes.
  // For patterns without *, the length is the length of the pattern (if it matches as a prefix).
  // For patterns with *, we need to be more careful.

  if (!pattern.includes("*") && !pattern.includes("$")) {
    // Literal prefix match
    if (path.startsWith(pattern)) return pattern.length;
    return 0;
  }

  if (pattern.endsWith("$") && !pattern.includes("*")) {
    // Exact match required
    const lit = pattern.slice(0, -1);
    if (path === lit) return lit.length;
    return 0;
  }

  // General case: use regex to match a prefix and find the consumed length.
  // We compile to a regex anchored at ^ but NOT ending with $ (unless $ is in the pattern).
  let reStr = "^";
  for (let i = 0; i < pattern.length; i++) {
    const ch = pattern[i];
    if (ch === "*") {
      reStr += ".*";
    } else if (ch === "$" && i === pattern.length - 1) {
      reStr += "$";
    } else {
      reStr += ch.replace(/[.+?^${}()|[\]\\]/g, "\\$&");
    }
  }
  // We want to find the LONGEST path prefix that the regex matches.
  // The simplest correct approach: try matching the regex against path[0:k] for
  // k from path.length down to 0, return the first k that matches.
  const re = new RegExp(reStr);
  for (let k = path.length; k >= 0; k--) {
    if (re.test(path.slice(0, k))) {
      return k;
    }
  }
  return 0;
}

// ---------- Test a URL against the rules (RFC 9309 §2.2.1 + §2.2.2) ----------

/**
 * Find the most specific user-agent group for the given agent.
 * Per RFC 9309 §2.2.1: select the group whose user-agent is the longest
 * left-to-right matching prefix of the request agent (case-insensitive).
 * If none match, the "*" group is used.
 */
export function selectGroup(availableGroups: string[], requestAgent: string): string {
  const req = normalizeAgent(requestAgent).toLowerCase();
  let best: string | null = null;
  let bestLen = -1;
  for (const g of availableGroups) {
    const gNorm = normalizeAgent(g).toLowerCase();
    if (gNorm === "*") continue;
    if (req === gNorm) {
      // exact match — can't beat this
      return g;
    }
    if (req.startsWith(gNorm) && gNorm.length > bestLen) {
      best = g;
      bestLen = gNorm.length;
    }
  }
  return best ?? (availableGroups.includes("*") || availableGroups.includes("") ? "*" : best ?? "*");
}

/**
 * Test a URL + user-agent against the rules. Returns the decision + the
 * deciding rule. Implements longest-match-wins with Allow > Disallow on ties.
 */
export function testUrl(options: RobotsTxtOptions, url: string, userAgent: string): TestResult {
  const extracted = extractPathFromUrl(url);
  if (!extracted.ok) {
    return {
      url, userAgent, allowed: true,
      matchedGroup: "*",
      reason: `Could not parse URL: ${extracted.reason}`,
    };
  }
  const path = extracted.path || "/";

  // 1. Find available user-agent groups
  const groups = new Set<string>();
  for (const r of options.rules) groups.add(normalizeAgent(r.userAgent));
  for (const cd of options.crawlDelays) groups.add(normalizeAgent(cd.userAgent));
  const groupArr = Array.from(groups);

  // 2. Select the most specific group
  const selectedGroup = selectGroup(groupArr, userAgent);

  // 3. Collect all rules for this group
  const rulesForGroup = options.rules.filter((r) => normalizeAgent(r.userAgent) === selectedGroup);

  if (rulesForGroup.length === 0) {
    return {
      url, userAgent, allowed: true,
      matchedGroup: selectedGroup,
      reason: `No rules for user-agent "${selectedGroup}" — default allow.`,
    };
  }

  // 4. Find the longest match across allow + disallow rules
  let bestAllow: { rule: Rule; length: number } | null = null;
  let bestDisallow: { rule: Rule; length: number } | null = null;

  for (const r of rulesForGroup) {
    const len = matchPath(r.path, path);
    if (len === 0) continue;
    if (r.type === "allow") {
      if (!bestAllow || len > bestAllow.length) bestAllow = { rule: r, length: len };
    } else {
      if (!bestDisallow || len > bestDisallow.length) bestDisallow = { rule: r, length: len };
    }
  }

  // 5. Decide: longest match wins; on tie, Allow > Disallow (RFC 9309 §2.2.2)
  // Edge cases:
  // - Empty Disallow path (Disallow: ) means "allow all" — represented as a 0-length allow.
  // - Empty Allow path (Allow: ) means "allow all" too.
  // - If no match at all: allow.
  if (!bestAllow && !bestDisallow) {
    return {
      url, userAgent, allowed: true,
      matchedGroup: selectedGroup,
      reason: `No rule matched path "${path}" for "${selectedGroup}" — default allow.`,
    };
  }

  let winner: Rule;
  let winnerLength: number;
  let allowed: boolean;

  if (bestAllow && bestDisallow) {
    if (bestAllow.length > bestDisallow.length) {
      winner = bestAllow.rule; winnerLength = bestAllow.length; allowed = true;
    } else if (bestDisallow.length > bestAllow.length) {
      winner = bestDisallow.rule; winnerLength = bestDisallow.length; allowed = false;
    } else {
      // tie — Allow wins
      winner = bestAllow.rule; winnerLength = bestAllow.length; allowed = true;
    }
  } else if (bestAllow) {
    winner = bestAllow.rule; winnerLength = bestAllow.length; allowed = true;
  } else {
    winner = (bestDisallow as { rule: Rule; length: number }).rule;
    winnerLength = (bestDisallow as { rule: Rule; length: number }).length;
    allowed = false;
  }

  return {
    url,
    userAgent,
    allowed,
    matchedRule: winner,
    matchedGroup: selectedGroup,
    reason: `${allowed ? "ALLOWED" : "BLOCKED"} by ${winner.type} ${winner.path} (matched ${winnerLength} char${winnerLength === 1 ? "" : "s"} of "${path}" in group "${selectedGroup}")`,
  };
}

// ---------- Build robots.txt text ----------

/** Group rules by user-agent for output. */
export function groupRules(rules: Rule[]): Map<string, Rule[]> {
  const map = new Map<string, Rule[]>();
  for (const r of rules) {
    const ua = normalizeAgent(r.userAgent);
    if (!map.has(ua)) map.set(ua, []);
    map.get(ua)!.push(r);
  }
  return map;
}

/** Generate the robots.txt text + warnings + explanations. */
export function generateRobots(options: RobotsTxtOptions): GeneratedRobots {
  const warnings: RiskWarning[] = [];
  const explanations: DirectiveExplanation[] = [];
  const lines: string[] = [];

  // 1. Header comments
  for (const c of options.headerComments) {
    if (c.trim()) lines.push(`# ${c}`);
  }
  if (options.headerComments.length > 0) lines.push("");

  // 2. AI-crawler block (one-click) — prepend a block-all group for each AI crawler
  let rules = options.rules;
  if (options.blockAllAiCrawlers) {
    const aiAgents = AI_CRAWLER_PRESETS.filter((p) => p.defaultBlock).map((p) => p.userAgent);
    const existingAgents = new Set(options.rules.map((r) => normalizeAgent(r.userAgent)));
    const extra: Rule[] = [];
    for (const ua of aiAgents) {
      if (!existingAgents.has(ua)) {
        extra.push({ id: genId(), userAgent: ua, type: "disallow", path: "/" });
      }
    }
    rules = [...extra, ...options.rules];
  }

  // 3. Validate + group rules
  const grouped = groupRules(rules);
  const seenGroups = new Set<string>();

  // Sort groups: order doesn't matter for RFC 9309 but "*" goes last by convention
  const groupKeys = Array.from(grouped.keys()).sort((a, b) => {
    if (a === "*" && b !== "*") return 1;
    if (b === "*" && a !== "*") return -1;
    return a.localeCompare(b);
  });

  for (const ua of groupKeys) {
    const uaRules = grouped.get(ua)!;
    // Validate user-agent
    const uaCheck = validateAgent(ua);
    if (!uaCheck.ok) {
      warnings.push({ level: "danger", message: `Invalid user-agent "${ua}": ${uaCheck.reason}`, directive: "User-agent" });
    }
    lines.push(`User-agent: ${ua}`);
    if (!seenGroups.has(ua)) {
      explanations.push({
        directive: "User-agent",
        value: ua,
        explanation: ua === "*"
          ? "Applies to all crawlers that don't have a more specific group."
          : `Targets the ${ua} crawler specifically. RFC 9309 §2.2.1: longest left-to-right prefix match decides which group applies.`,
      });
      seenGroups.add(ua);
    }

    for (const r of uaRules) {
      const pathCheck = validatePath(r.path);
      if (!pathCheck.ok) {
        warnings.push({ level: "danger", message: `Invalid path "${r.path}" for ${ua}: ${pathCheck.reason}`, directive: r.type });
        continue;
      }
      // Skip "Disallow: /" if it's the only rule and the agent is "*" — that's a danger
      if (r.type === "disallow" && r.path === "/" && ua === "*") {
        warnings.push({
          level: "danger",
          message: `Disallow: / for User-agent: * blocks ALL crawlers from your ENTIRE site. Only do this intentionally.`,
          directive: "Disallow",
        });
      }
      if (r.type === "disallow" && r.path === "/") {
        warnings.push({
          level: "warn",
          message: `Disallow: / for ${ua} blocks that crawler from your entire site.`,
          directive: "Disallow",
        });
      }
      lines.push(`${r.type === "allow" ? "Allow" : "Disallow"}: ${r.path}`);
      explanations.push({
        directive: r.type === "allow" ? "Allow" : "Disallow",
        value: r.path,
        explanation: r.type === "allow"
          ? `Explicitly permits ${ua} to crawl URLs matching "${r.path}". Allow wins ties with Disallow (RFC 9309 §2.2.2).`
          : `Blocks ${ua} from crawling URLs matching "${r.path}". Use * for wildcards and $ for end-of-URL anchor.`,
      });
    }

    // 4. Crawl-delay (per group)
    const cd = options.crawlDelays.find((d) => normalizeAgent(d.userAgent) === ua);
    if (cd) {
      lines.push(`Crawl-delay: ${cd.delay}`);
      warnings.push({
        level: "warn",
        message: `Crawl-delay is ignored by Googlebot. Bingbot/YandexBot honor it (0–30s). Use server-side rate limiting for real control.`,
        directive: "Crawl-delay",
      });
      explanations.push({
        directive: "Crawl-delay",
        value: String(cd.delay),
        explanation: `Requests ${ua} to wait ${cd.delay} seconds between requests. Not part of RFC 9309 — supported by some crawlers (Bing, Yandex) but ignored by Googlebot.`,
      });
    }

    lines.push(""); // blank line between groups
  }

  // 5. Sitemaps (always at the end, not inside any group)
  for (const s of options.sitemaps) {
    const check = validateSitemap(s);
    if (!check.ok) {
      warnings.push({ level: "danger", message: `Invalid sitemap URL "${s}": ${check.reason}`, directive: "Sitemap" });
      continue;
    }
    lines.push(`Sitemap: ${s}`);
    explanations.push({
      directive: "Sitemap",
      value: s,
      explanation: "Tells crawlers where your XML sitemap lives. Not part of RFC 9309 but widely supported. Multiple Sitemap lines are allowed.",
    });
  }
  if (options.sitemaps.length > 0) lines.push("");

  // 6. Honest note about unsupported directives
  warnings.push({
    level: "ok",
    message: "robots.txt controls crawling, NOT indexing or secrecy. Use noindex meta tags / X-Robots-Tag headers to control indexing. Use server-side auth to actually hide content.",
  });
  warnings.push({
    level: "ok",
    message: "Google ignores noindex and crawl-delay directives inside robots.txt. They are not part of RFC 9309 and will be flagged if you add them.",
  });

  return {
    options: { ...options, rules },
    text: lines.join("\n"),
    warnings,
    explanations,
  };
}

// ---------- Count warnings ----------

export function countWarnings(warnings: RiskWarning[]): { ok: number; warn: number; danger: number } {
  return {
    ok: warnings.filter((w) => w.level === "ok").length,
    warn: warnings.filter((w) => w.level === "warn").length,
    danger: warnings.filter((w) => w.level === "danger").length,
  };
}

// ---------- Plain-language intent parser ----------

export interface NlParseResult {
  options: Partial<RobotsTxtOptions>;
  notes: string[];
  unrecognized: string[];
}

/**
 * Parse plain-language intent into robots.txt options.
 * Recognized phrases (case-insensitive):
 *   - "block all ai training crawlers" / "block ai crawlers" → blockAllAiCrawlers = true
 *   - "allow <agent>" → adds Allow: / for that agent
 *   - "block <agent>" / "disallow <agent>" → adds Disallow: / for that agent
 *   - "disallow <path>" / "block <path>" (path starts with /) → Disallow rule for *
 *   - "allow <path>" (path starts with /) → Allow rule for *
 *   - "disallow <path> for <agent>" → Disallow for that agent
 *   - "crawl-delay <n>" / "crawl delay <n>" → Crawl-delay: n for *
 *   - "sitemap <url>" → add sitemap
 *   - "comment <text>" → add header comment
 */
export function parseIntent(input: string): NlParseResult {
  const options: Partial<RobotsTxtOptions> = {
    rules: [],
    crawlDelays: [],
    sitemaps: [],
    headerComments: [],
    blockAllAiCrawlers: false,
  };
  const notes: string[] = [];
  const unrecognized: string[] = [];
  if (!input || !input.trim()) return { options, notes, unrecognized };

  // Split on newlines, semicolons, or "and then"
  const lines = input
    .split(/\n|;|\bthen\b|\band\b/i)
    .map((s) => s.trim())
    .filter(Boolean);

  for (const line of lines) {
    const lower = line.toLowerCase();
    // Block all AI training crawlers
    if (/^block\s+all\s+ai(\s+training)?\s+crawlers?\b/.test(lower) ||
        /^block\s+ai\s+crawlers?\b/.test(lower) ||
        /^disallow\s+all\s+ai(\s+training)?\s+crawlers?\b/.test(lower)) {
      options.blockAllAiCrawlers = true;
      notes.push("→ Block all AI training crawlers: enabled");
      continue;
    }
    // Crawl-delay N (seconds)
    let m = lower.match(/^crawl[- ]?delay\s+(\d+)\s*(?:seconds?|secs?|s)?$/);
    if (m) {
      const delay = parseInt(m[1], 10);
      options.crawlDelays!.push({ id: genId(), userAgent: "*", delay });
      notes.push(`→ Crawl-delay: ${delay}s for *`);
      continue;
    }
    // Sitemap <url>
    m = lower.match(/^sitemap\s+(https?:\/\/\S+)$/i);
    if (m) {
      options.sitemaps!.push(m[1]);
      notes.push(`→ Sitemap: ${m[1]}`);
      continue;
    }
    // Comment <text>
    m = lower.match(/^comment\s+(.+)$/);
    if (m) {
      options.headerComments!.push(m[1]);
      notes.push(`→ Comment added`);
      continue;
    }
    // Allow/Block/Disallow <path> [for <agent>]
    m = lower.match(/^(allow|disallow|block)\s+(\S+)(?:\s+for\s+(\S+))?$/);
    if (m) {
      const type: RuleType = m[1] === "allow" ? "allow" : "disallow";
      const target = m[2];
      const agent = m[3] || "*";
      // Is target a path (starts with /) or an agent name (no leading /)?
      if (target.startsWith("/")) {
        const pathCheck = validatePath(target);
        if (!pathCheck.ok) {
          unrecognized.push(`Invalid path "${target}": ${pathCheck.reason}`);
          continue;
        }
        options.rules!.push({ id: genId(), userAgent: agent, type, path: target });
        notes.push(`→ ${type === "allow" ? "Allow" : "Disallow"}: ${target} for ${agent}`);
        continue;
      } else {
        // Target is an agent — implicitly path "/"
        const agentCheck = validateAgent(target);
        if (!agentCheck.ok) {
          unrecognized.push(`Invalid agent "${target}": ${agentCheck.reason}`);
          continue;
        }
        options.rules!.push({ id: genId(), userAgent: target, type, path: "/" });
        notes.push(`→ ${type === "allow" ? "Allow" : "Disallow"}: / for ${target}`);
        continue;
      }
    }
    // Bare "allow <agent>" pattern with no path
    m = lower.match(/^(allow|disallow|block)\s+(\w[\w.-]*)$/);
    if (m) {
      const type: RuleType = m[1] === "allow" ? "allow" : "disallow";
      const agent = m[2];
      const agentCheck = validateAgent(agent);
      if (agentCheck.ok) {
        options.rules!.push({ id: genId(), userAgent: agent, type, path: "/" });
        notes.push(`→ ${type === "allow" ? "Allow" : "Disallow"}: / for ${agent}`);
        continue;
      }
    }
    unrecognized.push(`Unrecognized: "${line}"`);
  }

  return { options, notes, unrecognized };
}

// ---------- Import existing robots.txt ----------

export function parseRobotsText(text: string): ParseResult {
  const options: RobotsTxtOptions = {
    rules: [],
    crawlDelays: [],
    sitemaps: [],
    headerComments: [],
    blockAllAiCrawlers: false,
  };
  const warnings: RiskWarning[] = [];
  const unknownDirectives: string[] = [];

  if (!text || !text.trim()) {
    return { options, warnings, unknownDirectives };
  }

  const lines = text.split("\n");
  let currentGroup: string | null = null;
  let groupAgents: string[] = [];

  for (let raw of lines) {
    const line = raw.trim();
    if (line === "") {
      // Blank line ends the current group
      currentGroup = null;
      groupAgents = [];
      continue;
    }
    if (line.startsWith("#")) {
      options.headerComments.push(line.slice(1).trim());
      continue;
    }
    const colonIdx = line.indexOf(":");
    if (colonIdx === -1) {
      warnings.push({ level: "warn", message: `Line without ":" — ignored: "${line}"` });
      continue;
    }
    const field = line.slice(0, colonIdx).trim().toLowerCase();
    const value = line.slice(colonIdx + 1).trim();

    if (field === "user-agent") {
      // Consecutive User-agent lines accumulate into the same group
      if (currentGroup === null) groupAgents = [];
      currentGroup = "active";
      groupAgents.push(value || "*");
    } else if (field === "allow" || field === "disallow") {
      if (groupAgents.length === 0) {
        warnings.push({ level: "warn", message: `${field} without preceding User-agent — ignored: "${line}"` });
        continue;
      }
      // Empty value means "allow all" — skip storing it but note it
      if (value === "") {
        // Disallow: (empty) means allow all — only meaningful if you want to override
        continue;
      }
      for (const ua of groupAgents) {
        options.rules.push({ id: genId(), userAgent: ua, type: field as RuleType, path: value });
      }
    } else if (field === "crawl-delay") {
      const delay = parseInt(value, 10);
      if (isNaN(delay) || delay < 0) {
        warnings.push({ level: "danger", message: `Invalid Crawl-delay value: "${value}"` });
        continue;
      }
      if (groupAgents.length === 0) {
        warnings.push({ level: "warn", message: `Crawl-delay without preceding User-agent — ignored: "${line}"` });
        continue;
      }
      for (const ua of groupAgents) {
        options.crawlDelays.push({ id: genId(), userAgent: ua, delay });
      }
    } else if (field === "sitemap") {
      const check = validateSitemap(value);
      if (!check.ok) {
        warnings.push({ level: "danger", message: `Invalid Sitemap URL: "${value}"` });
        continue;
      }
      options.sitemaps.push(value);
    } else if (field === "noindex") {
      warnings.push({ level: "warn", message: `noindex is NOT supported in robots.txt (Google deprecated it in 2019). Use meta robots or X-Robots-Tag instead. Line ignored.` });
      unknownDirectives.push("noindex");
    } else if (field === "host") {
      warnings.push({ level: "warn", message: `host directive is non-standard (Yandex-only). Ignored.` });
      unknownDirectives.push("host");
    } else if (field === "clean-param") {
      warnings.push({ level: "warn", message: `clean-param is Yandex-only. Ignored.` });
      unknownDirectives.push("clean-param");
    } else {
      unknownDirectives.push(field);
      warnings.push({ level: "warn", message: `Unknown directive "${field}" — ignored.` });
    }
  }

  return { options, warnings, unknownDirectives };
}

// ---------- Render ----------

/** Render a rule as a single-line summary. */
export function renderRule(r: Rule): string {
  return `${r.userAgent === "*" ? "*" : r.userAgent}: ${r.type === "allow" ? "Allow" : "Disallow"} ${r.path}`;
}

// ---------- History (localStorage) ----------

export function loadHistory(): HistoryEntry[] {
  if (typeof localStorage === "undefined") return [];
  try {
    const raw = localStorage.getItem(HISTORY_KEY);
    if (!raw) return [];
    const arr = JSON.parse(raw) as HistoryEntry[];
    return Array.isArray(arr) ? arr.slice(0, HISTORY_MAX) : [];
  } catch {
    return [];
  }
}

export function saveHistory(entry: HistoryEntry): HistoryEntry[] {
  const next = [entry, ...loadHistory()].slice(0, HISTORY_MAX);
  if (typeof localStorage !== "undefined") {
    try {
      localStorage.setItem(HISTORY_KEY, JSON.stringify(next));
    } catch {
      // ignore
    }
  }
  return next;
}

export function clearHistory(): void {
  if (typeof localStorage === "undefined") return;
  try {
    localStorage.removeItem(HISTORY_KEY);
  } catch {
    // ignore
  }
}

// ---------- Shareable URL ----------

export function buildShareUrl(options: Partial<RobotsTxtOptions>): string {
  const params = new URLSearchParams();
  if (options.blockAllAiCrawlers !== undefined) {
    params.set("blockAllAi", options.blockAllAiCrawlers ? "1" : "0");
  }
  if (options.sitemaps && options.sitemaps.length > 0) {
    params.set("sitemaps", options.sitemaps.join(","));
  }
  if (options.rules && options.rules.length > 0) {
    // Compact encoding: "ua|type|path;ua|type|path"
    const r = options.rules
      .map((rule) => `${rule.userAgent}|${rule.type}|${rule.path}`)
      .join(";");
    params.set("rules", r);
  }
  if (options.crawlDelays && options.crawlDelays.length > 0) {
    const c = options.crawlDelays.map((cd) => `${cd.userAgent}|${cd.delay}`).join(";");
    params.set("crawlDelays", c);
  }
  if (options.headerComments && options.headerComments.length > 0) {
    params.set("comments", options.headerComments.join("|"));
  }
  if (typeof window === "undefined") return `?${params.toString()}`;
  return `${window.location.origin}${window.location.pathname}#${params.toString()}`;
}

export function parseShareUrl(hash: string): ShareState {
  const clean = hash.startsWith("#") ? hash.slice(1) : hash;
  if (!clean) return { options: {} };
  const params = new URLSearchParams(clean);
  const options: Partial<RobotsTxtOptions> = {
    rules: [],
    crawlDelays: [],
    sitemaps: [],
    headerComments: [],
    blockAllAiCrawlers: false,
  };

  const blockAi = params.get("blockAllAi");
  if (blockAi !== null) options.blockAllAiCrawlers = blockAi === "1" || blockAi === "true";

  const sitemaps = params.get("sitemaps");
  if (sitemaps) {
    options.sitemaps = sitemaps.split(",").filter(Boolean);
  }

  const rules = params.get("rules");
  if (rules) {
    options.rules = rules.split(";").filter(Boolean).map((chunk) => {
      const [ua, type, path] = chunk.split("|");
      return {
        id: genId(),
        userAgent: ua || "*",
        type: (type === "allow" ? "allow" : "disallow") as RuleType,
        path: path || "/",
      };
    });
  }

  const cds = params.get("crawlDelays");
  if (cds) {
    options.crawlDelays = cds.split(";").filter(Boolean).map((chunk) => {
      const [ua, delayStr] = chunk.split("|");
      const delay = parseInt(delayStr, 10);
      return { id: genId(), userAgent: ua || "*", delay: isNaN(delay) ? 0 : delay };
    });
  }

  const comments = params.get("comments");
  if (comments) {
    options.headerComments = comments.split("|").filter(Boolean);
  }

  return { options };
}

// ---------- LLM prompt (BYO key) ----------

export function buildLlmPrompt(options: RobotsTxtOptions): LlmPrompt {
  const aiAgents = AI_CRAWLER_PRESETS.map((p) => `${p.userAgent} (${p.vendor} — ${p.purpose})`).join("\n");
  return {
    system: "You are a senior SEO engineer specializing in robots.txt and AI-crawler control. Output a complete, valid robots.txt with inline # comments explaining each group. Use RFC 9309 syntax. Never use noindex or unsupported directives. Output only robots.txt — no markdown fences, no preamble.",
    user: `Generate a robots.txt with these requirements:
- Block all AI training crawlers (one-click): ${options.blockAllAiCrawlers ? "yes" : "no"}
- Sitemaps: ${options.sitemaps.length > 0 ? options.sitemaps.join(", ") : "(none)"}
- Explicit rules:
${options.rules.length > 0 ? options.rules.map((r) => `  - ${r.userAgent}: ${r.type} ${r.path}`).join("\n") : "  (none — use the AI-crawler toggle above)"}
- Crawl-delays:
${options.crawlDelays.length > 0 ? options.crawlDelays.map((cd) => `  - ${cd.userAgent}: ${cd.delay}s`).join("\n") : "  (none)"}

Modern AI-crawler user-agents (use these names exactly):
${aiAgents}

Remember: Googlebot ignores Crawl-delay and noindex inside robots.txt. Use the most specific Allow/Disallow per group. Add a Sitemap: line at the end if the user provided one. Include honest inline comments.`,
  };
}

export function renderLlmResult(raw: string): string {
  return raw.replace(/^```[\w]*\n?/g, "").replace(/\n?```$/g, "").trim();
}
