/**
 * PDF to PowerPoint Converter — pure-JS PPTX (OOXML Presentation) generator.
 *
 * Pipeline:
 *   1. Extract text from PDF using pdf-to-text-converter's extractor.
 *   2. Build slides: one slide per PDF page (title = first line, bullets = rest).
 *   3. Generate the OOXML ZIP structure:
 *        - [Content_Types].xml
 *        - _rels/.rels
 *        - ppt/presentation.xml
 *        - ppt/_rels/presentation.xml.rels
 *        - ppt/presProps.xml
 *        - ppt/viewProps.xml
 *        - ppt/theme/theme1.xml
 *        - ppt/slideMasters/slideMaster1.xml
 *        - ppt/slideMasters/_rels/slideMaster1.xml.rels
 *        - ppt/slideLayouts/slideLayout1.xml
 *        - ppt/slideLayouts/_rels/slideLayout1.xml.rels
 *        - ppt/slides/slide1.xml, slide2.xml, ...
 *        - ppt/slides/_rels/slideN.xml.rels
 *   4. Package everything into a ZIP (reuse createZipBlob).
 */

import {
  extractPdfText,
  formatBytes,
  type ConvertOptions as TextOptions,
} from "../pdf-to-text-converter/logic";
import {
  createZipBlob,
  type ZipFile,
  xmlEscape,
  xmlAttrEscape,
} from "../csv-to-excel-converter/logic";
import type { ToolResult } from "../../../lib/tool";

// ===== Types =====

export type SlideLayout = "title-content" | "content-only";

export interface PptxOptions {
  /** Page range (e.g. "1-3,5"). Empty = all pages. */
  pageRange: string;
  /** Slide layout. */
  layout: SlideLayout;
  /** Custom title slide title. */
  titleSlideTitle: string;
  /** Custom title slide subtitle. */
  titleSlideSubtitle: string;
  /** Insert a title slide as slide 1 (uses the values above). */
  insertTitleSlide: boolean;
  /** Base font size in points for body text. */
  fontSize: number;
  /** Slide aspect ratio. */
  aspectRatio: "16:9" | "4:3";
  /** Accent color for titles (hex without #). */
  accentColor: string;
}

export const DEFAULT_OPTIONS: PptxOptions = {
  pageRange: "",
  layout: "title-content",
  titleSlideTitle: "Converted from PDF",
  titleSlideSubtitle: "Generated by UnQTools",
  insertTitleSlide: true,
  fontSize: 18,
  aspectRatio: "16:9",
  accentColor: "1F4E79",
};

export interface SlideContent {
  /** 1-indexed slide number. */
  number: number;
  /** Slide title (empty for content-only). */
  title: string;
  /** Bullet point paragraphs. */
  bullets: string[];
  /** Word count. */
  wordCount: number;
}

export interface PptxResult {
  blob: Blob;
  fileName: string;
  slideCount: number;
  wordCount: number;
  charCount: number;
  pageCount: number;
  pptxBytes: number;
  slides: SlideContent[];
}

// ===== Slide dimensions =====

/** Get slide dimensions in EMUs (English Metric Units: 914400 per inch). */
export function getSlideDimensions(ratio: "16:9" | "4:3"): { width: number; height: number } {
  // PowerPoint standard: 16:9 = 13.333 x 7.5 inches; 4:3 = 10 x 7.5 inches
  if (ratio === "16:9") {
    return { width: 12192000, height: 6858000 }; // 13.333" x 7.5"
  }
  return { width: 9144000, height: 6858000 }; // 10" x 7.5"
}

// ===== Slide building =====

/**
 * Build slide content from PDF page texts.
 * Each page becomes one slide: first non-empty line is the title,
 * remaining lines are bullets. Empty lines become paragraph breaks.
 */
export function buildSlides(pageTexts: string[], opts: PptxOptions): SlideContent[] {
  const slides: SlideContent[] = [];
  let number = 1;
  if (opts.insertTitleSlide) {
    slides.push({
      number: number++,
      title: opts.titleSlideTitle,
      bullets: [opts.titleSlideSubtitle].filter((s) => s !== ""),
      wordCount: countWords(opts.titleSlideTitle + " " + opts.titleSlideSubtitle),
    });
  }
  for (const pageText of pageTexts) {
    const lines = pageText.split("\n").map((l) => l.trim()).filter((l) => l !== "");
    if (lines.length === 0) continue;
    const title = opts.layout === "title-content" ? lines[0]! : "";
    const bullets = opts.layout === "title-content" ? lines.slice(1) : lines;
    slides.push({
      number: number++,
      title,
      bullets,
      wordCount: countWords(lines.join(" ")),
    });
  }
  return slides;
}

export function countWords(text: string): number {
  return text.split(/\s+/).filter((s) => s.length > 0).length;
}

// ===== Slide XML generation =====

const SLIDE_NS = "http://schemas.openxmlformats.org/presentationml/2006/main";
const REL_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";

/** Generate a slide XML for a title + content layout. */
export function generateSlideXml(slide: SlideContent, opts: PptxOptions, isTitleSlide: boolean = false): string {
  const dims = getSlideDimensions(opts.aspectRatio);
  const fs = Math.max(10, Math.min(60, opts.fontSize));
  const titleFs = Math.max(20, fs + 12);
  const accent = opts.accentColor.replace(/^#/, "").toUpperCase();
  const titleColor = `FF${accent}`;
  // Title text box — top of slide
  const titleBox = isTitleSlide
    ? generateTitleSlideTitle(slide.title, dims, titleFs, titleColor)
    : opts.layout === "title-content"
      ? generateTitleBox(slide.title, dims, titleFs, titleColor)
      : "";
  // Content / bullets
  let contentBox: string;
  if (isTitleSlide) {
    contentBox = generateTitleSlideSubtitle(slide.bullets[0] ?? "", dims, fs);
  } else {
    const top = opts.layout === "title-content" ? 1828800 : 457200;
    const height = opts.layout === "title-content" ? 4572000 : 5486400;
    contentBox = generateContentBox(slide.bullets, dims, top, height, fs);
  }
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${REL_NS}" xmlns:p="${SLIDE_NS}">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${dims.width}" cy="${dims.height}"/><a:chOff x="0" y="0"/><a:chExt cx="${dims.width}" cy="${dims.height}"/></a:xfrm></p:grpSpPr>
${titleBox}
${contentBox}
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>`;
}

/** Generate the title text box for a content slide. */
function generateTitleBox(title: string, dims: { width: number; height: number }, fontSize: number, color: string): string {
  const x = 457200; // 0.5 inch
  const y = 274320; // 0.3 inch
  const w = dims.width - 914400;
  const h = 1143000; // 1.25 inch
  const escaped = xmlEscape(title);
  return `      <p:sp>
        <p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr><p:ph type="title"/></p:nvPr></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="${x}" y="${y}"/><a:ext cx="${w}" cy="${h}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr>
        <p:txBody><a:bodyPr wrap="square" anchor="t"/><a:lstStyle/>
          <a:p><a:r><a:rPr lang="en-US" sz="${fontSize * 100}" b="1"><a:solidFill><a:srgbClr val="${color}"/></a:solidFill></a:rPr><a:t>${escaped}</a:t></a:r></a:p>
        </p:txBody>
      </p:sp>`;
}

/** Generate the content/bullet text box. */
function generateContentBox(bullets: string[], dims: { width: number; height: number }, top: number, height: number, fontSize: number): string {
  const x = 457200;
  const w = dims.width - 914400;
  const escaped = bullets.length > 0 ? bullets.map((b) => {
    return `          <a:p><a:pPr marL="171450" indent="-171450"><a:buFont typeface="Arial"/><a:buChar char="•"/></a:pPr><a:r><a:rPr lang="en-US" sz="${fontSize * 100}"/><a:t>${xmlEscape(b)}</a:t></a:r></a:p>`;
  }).join("\n") : `          <a:p/>`;
  return `      <p:sp>
        <p:nvSpPr><p:cNvPr id="3" name="Content"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr><p:ph type="body" idx="1"/></p:nvPr></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="${x}" y="${top}"/><a:ext cx="${w}" cy="${height}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr>
        <p:txBody><a:bodyPr wrap="square" anchor="t"/>
          <a:lstStyle/>
${escaped}
        </p:txBody>
      </p:sp>`;
}

/** Title slide: large centered title. */
function generateTitleSlideTitle(title: string, dims: { width: number; height: number }, fontSize: number, color: string): string {
  const x = 914400;
  const w = dims.width - 1828800;
  const y = Math.floor(dims.height * 0.3);
  const h = 1143000;
  return `      <p:sp>
        <p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr><p:ph type="title"/></p:nvPr></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="${x}" y="${y}"/><a:ext cx="${w}" cy="${h}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr>
        <p:txBody><a:bodyPr wrap="square" anchor="ctr"/><a:lstStyle/>
          <a:p><a:pPr algn="ctr"/><a:r><a:rPr lang="en-US" sz="${fontSize * 100}" b="1"><a:solidFill><a:srgbClr val="${color}"/></a:solidFill></a:rPr><a:t>${xmlEscape(title)}</a:t></a:r></a:p>
        </p:txBody>
      </p:sp>`;
}

/** Title slide subtitle. */
function generateTitleSlideSubtitle(subtitle: string, dims: { width: number; height: number }, fontSize: number): string {
  const x = 1828800;
  const w = dims.width - 3657600;
  const y = Math.floor(dims.height * 0.55);
  const h = 914400;
  return `      <p:sp>
        <p:nvSpPr><p:cNvPr id="3" name="Subtitle"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr><p:ph type="body" idx="1"/></p:nvPr></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="${x}" y="${y}"/><a:ext cx="${w}" cy="${h}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr>
        <p:txBody><a:bodyPr wrap="square" anchor="ctr"/><a:lstStyle/>
          <a:p><a:pPr algn="ctr"/><a:r><a:rPr lang="en-US" sz="${fontSize * 100}"/><a:t>${xmlEscape(subtitle)}</a:t></a:r></a:p>
        </p:txBody>
      </p:sp>`;
}

// ===== Top-level PPTX XML =====

export function generatePresentationXml(slideCount: number, opts: PptxOptions): string {
  const dims = getSlideDimensions(opts.aspectRatio);
  const sldIds = Array.from({ length: slideCount }, (_, i) => {
    return `    <p:sldId id="${256 + i}" r:id="rId${i + 2}"/>`;
  }).join("\n");
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${REL_NS}" xmlns:p="${SLIDE_NS}" saveSubsetFonts="1">
  <p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst>
  <p:sldIdLst>
${sldIds}
  </p:sldIdLst>
  <p:sldSz cx="${dims.width}" cy="${dims.height}" type="screen${opts.aspectRatio.replace(":", "x")}"/>
  <p:notesSz cx="6858000" cy="9144000"/>
  <p:defaultTextStyle/>
</p:presentation>`;
}

export function generateContentTypesXml(slideCount: number): string {
  const slideOverrides = Array.from({ length: slideCount }, (_, i) => {
    return `<Override PartName="/ppt/slides/slide${i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`;
  }).join("");
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
  <Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/>
  <Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/>
  <Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>
  <Override PartName="/ppt/presProps.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presProps+xml"/>
  <Override PartName="/ppt/viewProps.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.viewProps+xml"/>
  ${slideOverrides}
</Types>`;
}

export function generateRootRelsXml(): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
</Relationships>`;
}

export function generatePresentationRelsXml(slideCount: number): string {
  const slideRels = Array.from({ length: slideCount }, (_, i) => {
    return `<Relationship Id="rId${i + 2}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${i + 1}.xml"/>`;
  }).join("");
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>
  ${slideRels}
</Relationships>`;
}

export function generateSlideRelsXml(): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>
</Relationships>`;
}

export function generateSlideMasterXml(): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${REL_NS}" xmlns:p="${SLIDE_NS}">
  <p:cSld><p:bg><p:bgRef idx="1001"><a:schemeClr val="bg1"/></p:bgRef></p:bg>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="12192000" cy="6858000"/><a:chOff x="0" y="0"/><a:chExt cx="12192000" cy="6858000"/></a:xfrm></p:grpSpPr>
    </p:spTree>
  </p:cSld>
  <p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/>
  <p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="rId1"/></p:sldLayoutIdLst>
  <p:txStyles>
    <p:titleStyle><a:lvl1pPr algn="l"><a:spcBef><a:spcPct val="20000"/></a:spcBef><a:buNone/><a:defRPr sz="4400" b="1"/></a:lvl1pPr></p:titleStyle>
    <p:bodyStyle><a:lvl1pPr><a:spcBef><a:spcPct val="20000"/></a:spcBef><a:buFont typeface="Arial" panose="020B0604020202020204"/><a:buChar char="•"/></a:lvl1pPr></p:bodyStyle>
    <p:otherStyle/>
  </p:txStyles>
</p:sldMaster>`;
}

export function generateSlideMasterRelsXml(): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/>
</Relationships>`;
}

export function generateSlideLayoutXml(): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${REL_NS}" xmlns:p="${SLIDE_NS}" type="title" preserve="1">
  <p:cSld name="Title Slide">
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="12192000" cy="6858000"/><a:chOff x="0" y="0"/><a:chExt cx="12192000" cy="6858000"/></a:xfrm></p:grpSpPr>
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sldLayout>`;
}

export function generateSlideLayoutRelsXml(): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/>
</Relationships>`;
}

export function generateThemeXml(opts: PptxOptions): string {
  const accent = opts.accentColor.replace(/^#/, "").toUpperCase();
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="UnQTools Theme">
  <a:themeElements>
    <a:clrScheme name="Office">
      <a:dk1><a:sysClr val="windowText" lastClr="000000"/></a:dk1>
      <a:lt1><a:sysClr val="window" lastClr="FFFFFF"/></a:lt1>
      <a:dk2><a:srgbClr val="44546A"/></a:dk2>
      <a:lt2><a:srgbClr val="E7E6E6"/></a:lt2>
      <a:accent1><a:srgbClr val="${accent}"/></a:accent1>
      <a:accent2><a:srgbClr val="ED7D31"/></a:accent2>
      <a:accent3><a:srgbClr val="A5A5A5"/></a:accent3>
      <a:accent4><a:srgbClr val="FFC000"/></a:accent4>
      <a:accent5><a:srgbClr val="5B9BD5"/></a:accent5>
      <a:accent6><a:srgbClr val="70AD47"/></a:accent6>
      <a:hlink><a:srgbClr val="0563C1"/></a:hlink>
      <a:folHlink><a:srgbClr val="954F72"/></a:folHlink>
    </a:clrScheme>
    <a:fontScheme name="Office"><a:majorFont><a:latin typeface="Calibri Light"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont><a:minorFont><a:latin typeface="Calibri"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont></a:fontScheme>
    <a:fmtScheme name="Office">
      <a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:fillStyleLst>
      <a:lnStyleLst><a:ln w="9525" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:prstDash val="solid"/></a:ln><a:ln w="25400" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:prstDash val="solid"/></a:ln><a:ln w="38100" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:prstDash val="solid"/></a:ln></a:lnStyleLst>
      <a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst>
      <a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:bgFillStyleLst>
    </a:fmtScheme>
  </a:themeElements>
</a:theme>`;
}

export function generatePresPropsXml(): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentationPr xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${REL_NS}" xmlns:p="${SLIDE_NS}"/>`;
}

export function generateViewPropsXml(): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:viewPr xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${REL_NS}" xmlns:p="${SLIDE_NS}">
  <p:normalViewPr><p:restoredLeft sz="15620"/><p:restoredTop sz="94660"/></p:normalViewPr>
  <p:slideViewPr><p:cSldViewPr><p:cViewPr varScale="1"><p:scale><a:sx n="64" d="100"/><a:sy n="64" d="100"/></p:scale><p:origin x="-1392" y="-96"/></p:cViewPr></p:cSldViewPr></p:slideViewPr>
</p:viewPr>`;
}

// ===== Top-level conversion =====

export async function convertPdfToPptx(
  pdfBytes: Uint8Array,
  opts: PptxOptions = DEFAULT_OPTIONS,
  outputFileName: string = "converted.pptx",
): Promise<ToolResult<PptxResult>> {
  const textOptions: TextOptions = {
    pageRange: opts.pageRange,
    lineSeparator: "\n",
    pageSeparator: "",
    trimLines: true,
    removeEmptyLines: false,
    lineNumbers: false,
    addBom: false,
  };
  const textResult = await extractPdfText(pdfBytes, textOptions);
  if (!textResult.ok) {
    return { ok: false, error: textResult.error };
  }
  const pageTexts = textResult.output.pages.map((p) => p.text);
  const slides = buildSlides(pageTexts, opts);
  if (slides.length === 0) {
    return { ok: false, error: "No text content found in the PDF." };
  }
  const enc = new TextEncoder();
  const files: ZipFile[] = [];
  files.push({ name: "[Content_Types].xml", data: enc.encode(generateContentTypesXml(slides.length)) });
  files.push({ name: "_rels/.rels", data: enc.encode(generateRootRelsXml()) });
  files.push({ name: "ppt/presentation.xml", data: enc.encode(generatePresentationXml(slides.length, opts)) });
  files.push({ name: "ppt/_rels/presentation.xml.rels", data: enc.encode(generatePresentationRelsXml(slides.length)) });
  files.push({ name: "ppt/presProps.xml", data: enc.encode(generatePresPropsXml()) });
  files.push({ name: "ppt/viewProps.xml", data: enc.encode(generateViewPropsXml()) });
  files.push({ name: "ppt/theme/theme1.xml", data: enc.encode(generateThemeXml(opts)) });
  files.push({ name: "ppt/slideMasters/slideMaster1.xml", data: enc.encode(generateSlideMasterXml()) });
  files.push({ name: "ppt/slideMasters/_rels/slideMaster1.xml.rels", data: enc.encode(generateSlideMasterRelsXml()) });
  files.push({ name: "ppt/slideLayouts/slideLayout1.xml", data: enc.encode(generateSlideLayoutXml()) });
  files.push({ name: "ppt/slideLayouts/_rels/slideLayout1.xml.rels", data: enc.encode(generateSlideLayoutRelsXml()) });
  for (const slide of slides) {
    const isTitleSlide = opts.insertTitleSlide && slide.number === 1;
    files.push({ name: `ppt/slides/slide${slide.number}.xml`, data: enc.encode(generateSlideXml(slide, opts, isTitleSlide)) });
    files.push({ name: `ppt/slides/_rels/slide${slide.number}.xml.rels`, data: enc.encode(generateSlideRelsXml()) });
  }
  const blob = createZipBlob(files);
  const wordCount = slides.reduce((s, sl) => s + sl.wordCount, 0);
  const charCount = slides.reduce((s, sl) => s + sl.title.length + sl.bullets.join(" ").length, 0);
  return {
    ok: true,
    output: {
      blob,
      fileName: outputFileName,
      slideCount: slides.length,
      wordCount,
      charCount,
      pageCount: textResult.output.pageCount,
      pptxBytes: blob.size,
      slides,
    },
  };
}

// ===== Utilities =====

export { formatBytes, xmlEscape, xmlAttrEscape };

// ===== History =====

const HISTORY_KEY = "unqtools-pdf-to-pptx-history";
const MAX_HISTORY = 10;

export interface HistoryEntry {
  fileName: string;
  pdfBytes: number;
  pptxBytes: number;
  slideCount: number;
  wordCount: number;
  convertedAt: string;
}

export function loadHistory(): HistoryEntry[] {
  if (typeof localStorage === "undefined") return [];
  try {
    const raw = localStorage.getItem(HISTORY_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.slice(0, MAX_HISTORY) : [];
  } catch { return []; }
}

export function saveToHistory(entry: HistoryEntry): HistoryEntry[] {
  if (typeof localStorage === "undefined") return [];
  const updated = [entry, ...loadHistory()].slice(0, MAX_HISTORY);
  try { localStorage.setItem(HISTORY_KEY, JSON.stringify(updated)); } catch { /* ignore */ }
  return updated;
}

export function clearHistory(): void {
  if (typeof localStorage === "undefined") return;
  try { localStorage.removeItem(HISTORY_KEY); } catch { /* ignore */ }
}

// ===== Shareable URL =====

export function buildShareUrl(opts: PptxOptions): string {
  if (typeof window === "undefined") return "";
  const params = new URLSearchParams();
  if (opts.pageRange) params.set("pages", opts.pageRange);
  params.set("layout", opts.layout);
  params.set("title", opts.insertTitleSlide ? "1" : "0");
  params.set("fs", String(opts.fontSize));
  params.set("ratio", opts.aspectRatio);
  params.set("accent", opts.accentColor);
  return `${window.location.origin}${window.location.pathname}#${params.toString()}`;
}

export function parseShareUrl(hash: string): Partial<PptxOptions> | null {
  if (!hash || !hash.startsWith("#")) return null;
  const params = new URLSearchParams(hash.slice(1));
  if (!params.has("layout") && !params.has("pages")) return null;
  const layout = (params.get("layout") ?? "title-content") as SlideLayout;
  const validLayouts: SlideLayout[] = ["title-content", "content-only"];
  const fs = parseInt(params.get("fs") ?? "18", 10);
  const ratio = (params.get("ratio") ?? "16:9") as PptxOptions["aspectRatio"];
  const validRatios: PptxOptions["aspectRatio"][] = ["16:9", "4:3"];
  return {
    pageRange: params.get("pages") ?? "",
    layout: validLayouts.includes(layout) ? layout : "title-content",
    insertTitleSlide: params.get("title") !== "0",
    fontSize: isNaN(fs) ? 18 : Math.max(10, Math.min(60, fs)),
    aspectRatio: validRatios.includes(ratio) ? ratio : "16:9",
    accentColor: params.get("accent") ?? DEFAULT_OPTIONS.accentColor,
  };
}
