/**
 * EPUB to AZW3 Converter — pure-JS EPUB parser + AZW3 (KF8) generator.
 *
 * Pipeline:
 *   1. Parse EPUB (ZIP) using epub-reader's parseEpub.
 *   2. Extract chapter text from each XHTML chapter (strip HTML tags).
 *   3. Wrap chapter text in <h1>title</h1><p>para</p>... HTML.
 *   4. Generate AZW3 file using pdf-to-azw3-converter's assembleAzw3.
 */

import {
  parseEpub,
  stripXmlTags,
  extractBody,
  type EpubBook,
  type EpubChapter,
} from "../epub-reader/logic";
import {
  assembleAzw3,
  buildCoverPage,
  buildHtmlBody,
  splitTextRecords,
  escapeHtml,
  type Azw3Options,
  type Azw3Encoding,
  type Azw3ChapterMode,
} from "../pdf-to-azw3-converter/logic";
import type { ToolResult } from "../../../lib/tool";

// ===== Types =====

export interface EpubToAzw3Options {
  title: string;
  author: string;
  language: string;
  encoding: Azw3Encoding;
  chapterMode: Azw3ChapterMode;
  coverSubtitle: string;
}

export const DEFAULT_OPTIONS: EpubToAzw3Options = {
  title: "Converted from EPUB",
  author: "Unknown",
  language: "en",
  encoding: "utf-8",
  chapterMode: "page",
  coverSubtitle: "Generated by UnQTools EPUB to AZW3",
};

export interface EpubToAzw3Result {
  blob: Blob;
  fileName: string;
  metadata: { title: string; author: string; language: string };
  chapterCount: number;
  wordCount: number;
  charCount: number;
  recordCount: number;
  textRecordCount: number;
  azw3Bytes: number;
  previewText: string;
}

// ===== EPUB chapter to text =====

export function chapterToText(chapter: EpubChapter): string {
  const body = extractBody(chapter.content);
  return stripXmlTags(body);
}

export function chaptersToPageTexts(chapters: EpubChapter[]): string[] {
  return chapters.map((c) => {
    const title = c.title || `Chapter ${c.index + 1}`;
    const body = chapterToText(c);
    return `${title}\n${body}`;
  });
}

export function countWords(text: string): number {
  return text.split(/\s+/).filter((s) => s.length > 0).length;
}

// ===== Top-level conversion =====

export async function convertEpubToAzw3(
  epubBytes: Uint8Array,
  opts: EpubToAzw3Options = DEFAULT_OPTIONS,
  outputFileName: string = "converted.azw3",
): Promise<ToolResult<EpubToAzw3Result>> {
  let book: EpubBook;
  try {
    book = await parseEpub(epubBytes, outputFileName, epubBytes.length);
  } catch (e) {
    return { ok: false, error: `Could not parse EPUB: ${(e as Error).message}` };
  }
  if (book.chapters.length === 0) {
    return { ok: false, error: "EPUB has no chapters." };
  }
  const pageTexts = chaptersToPageTexts(book.chapters);
  if (pageTexts.every((p) => p.trim() === "")) {
    return { ok: false, error: "EPUB chapters contain no extractable text." };
  }

  const effectiveOpts: Azw3Options = {
    pageRange: "",
    title: opts.title && opts.title !== DEFAULT_OPTIONS.title
      ? opts.title
      : (book.metadata.title || DEFAULT_OPTIONS.title),
    author: opts.author && opts.author !== DEFAULT_OPTIONS.author
      ? opts.author
      : (book.metadata.author || DEFAULT_OPTIONS.author),
    coverSubtitle: opts.coverSubtitle,
    encoding: opts.encoding,
    chapterMode: opts.chapterMode,
    language: opts.language !== "en" ? opts.language : (book.metadata.language || "en"),
  };

  const azw3Bytes = assembleAzw3(pageTexts, effectiveOpts);
  const coverHtml = buildCoverPage(effectiveOpts);
  const bodyHtml = buildHtmlBody(pageTexts, effectiveOpts);
  const fullHtml = coverHtml + "\n<mbp:pagebreak/>\n" + bodyHtml;
  const textRecordCount = splitTextRecords(fullHtml, effectiveOpts.encoding).length;
  const totalText = pageTexts.join("\n");
  const wordCount = countWords(totalText);
  const charCount = totalText.length;
  const blob = new Blob([azw3Bytes as BlobPart], { type: "application/x-mobipocket-ebook" });

  return {
    ok: true,
    output: {
      blob,
      fileName: outputFileName,
      metadata: {
        title: effectiveOpts.title,
        author: effectiveOpts.author,
        language: effectiveOpts.language,
      },
      chapterCount: book.chapters.length,
      wordCount,
      charCount,
      recordCount: textRecordCount + 2, // +1 for record 0, +1 for boundary
      textRecordCount,
      azw3Bytes: azw3Bytes.length,
      previewText: pageTexts[0]?.slice(0, 2000) ?? "",
    },
  };
}

// ===== Utilities =====

export function formatBytes(bytes: number): string {
  if (bytes <= 0) return "0 B";
  const k = 1024;
  const units = ["B", "KB", "MB", "GB", "TB"];
  const i = Math.min(units.length - 1, Math.floor(Math.log(bytes) / Math.log(k)));
  return `${(bytes / Math.pow(k, i)).toFixed(i === 0 ? 0 : 1)} ${units[i]}`;
}

export { escapeHtml };

// ===== History (localStorage) =====

const HISTORY_KEY = "unqtools-epub-to-azw3-history";
const MAX_HISTORY = 10;

export interface HistoryEntry {
  fileName: string;
  epubBytes: number;
  azw3Bytes: number;
  chapterCount: number;
  wordCount: number;
  recordCount: number;
  convertedAt: string;
}

export function loadHistory(): HistoryEntry[] {
  if (typeof localStorage === "undefined") return [];
  try {
    const raw = localStorage.getItem(HISTORY_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.slice(0, MAX_HISTORY) : [];
  } catch {
    return [];
  }
}

export function saveToHistory(entry: HistoryEntry): HistoryEntry[] {
  if (typeof localStorage === "undefined") return [];
  const updated = [entry, ...loadHistory()].slice(0, MAX_HISTORY);
  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(updated));
  } catch {
    /* ignore */
  }
  return updated;
}

export function clearHistory(): void {
  if (typeof localStorage === "undefined") return;
  try {
    localStorage.removeItem(HISTORY_KEY);
  } catch {
    /* ignore */
  }
}

// ===== Shareable URL =====

export function buildShareUrl(opts: EpubToAzw3Options): string {
  if (typeof window === "undefined") return "";
  const params = new URLSearchParams();
  params.set("mode", opts.chapterMode);
  params.set("enc", opts.encoding);
  if (opts.title && opts.title !== DEFAULT_OPTIONS.title) params.set("title", opts.title);
  if (opts.author && opts.author !== DEFAULT_OPTIONS.author) params.set("author", opts.author);
  params.set("lang", opts.language);
  if (opts.coverSubtitle && opts.coverSubtitle !== DEFAULT_OPTIONS.coverSubtitle) {
    params.set("subtitle", opts.coverSubtitle);
  }
  return `${window.location.origin}${window.location.pathname}#${params.toString()}`;
}

export function parseShareUrl(hash: string): Partial<EpubToAzw3Options> | null {
  if (!hash || !hash.startsWith("#")) return null;
  const params = new URLSearchParams(hash.slice(1));
  if (!params.has("mode") && !params.has("enc")) return null;
  const mode = (params.get("mode") ?? "page") as Azw3ChapterMode;
  const validModes: Azw3ChapterMode[] = ["page", "heading", "single"];
  const enc = (params.get("enc") ?? "utf-8") as Azw3Encoding;
  const validEncs: Azw3Encoding[] = ["utf-8", "cp1252"];
  return {
    chapterMode: validModes.includes(mode) ? mode : "page",
    encoding: validEncs.includes(enc) ? enc : "utf-8",
    title: params.get("title") ?? "",
    author: params.get("author") ?? "",
    language: params.get("lang") ?? "en",
    coverSubtitle: params.get("subtitle") ?? "",
  };
}
