/**
 * PDF to AZW3 Converter — pure-JS simplified KF8 (Kindle Format 8) generator.
 *
 * AZW3 structure (simplified):
 *   1. PalmDB header (78 bytes) — type 'BOOK', creator 'MOBI'
 *   2. Record info table — recordCount × 8 bytes
 *   3. Padding (2 bytes)
 *   4. Records:
 *        - Record 0: PalmDOC header + MOBI header + EXTH + KF8 boundary marker
 *        - Record 1: Cover page HTML (simple <h1>title</h1><p>author</p>)
 *        - Records 2..N: HTML text records (max 4096 bytes each)
 *        - Last record: KF8 boundary 'BOUNDARY' marker
 *
 * Real AZW3 files have a much more complex structure (KF8 index, flow items,
 * vocab indexes, etc.). We produce a minimal readable subset.
 */

import {
  extractPdfText,
  formatBytes,
  type ConvertOptions as TextOptions,
} from "../pdf-to-text-converter/logic";
import {
  writeU16BE, writeU32BE, writeAscii, writePaddedAscii, readAscii,
} from "../pdf-to-mobi-converter/logic";
import type { ToolResult } from "../../../lib/tool";

// Re-export some helpers from mobi for convenience
export { writeU16BE, writeU32BE, writeAscii, writePaddedAscii, readAscii };

// ===== Types =====

export type Azw3Encoding = "utf-8" | "cp1252";
export type Azw3ChapterMode = "page" | "heading" | "single";

export interface Azw3Options {
  /** Page range (e.g. "1-3,5"). Empty = all pages. */
  pageRange: string;
  /** Book title. */
  title: string;
  /** Book author. */
  author: string;
  /** Cover page text (subtitle shown below title on the cover). */
  coverSubtitle: string;
  /** Text encoding. */
  encoding: Azw3Encoding;
  /** Chapter splitting mode. */
  chapterMode: Azw3ChapterMode;
  /** Language code. */
  language: string;
}

export const DEFAULT_OPTIONS: Azw3Options = {
  pageRange: "",
  title: "Converted from PDF",
  author: "UnQTools",
  coverSubtitle: "Generated by UnQTools PDF to AZW3",
  encoding: "utf-8",
  chapterMode: "page",
  language: "en",
};

export interface Azw3Result {
  blob: Blob;
  fileName: string;
  recordCount: number;
  textRecordCount: number;
  wordCount: number;
  charCount: number;
  pageCount: number;
  azw3Bytes: number;
}

// ===== Constants =====

const TEXT_RECORD_SIZE = 4096;
const PALMDB_HEADER_SIZE = 78;
const RECORD_INFO_SIZE = 8;
const PALMDOC_HEADER_SIZE = 16;
const MOBI_HEADER_SIZE = 232;
const KF8_BOUNDARY_MARKER = "BOUNDARY";

// ===== HTML escaping =====

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// ===== Heading detection (shared logic with mobi) =====

export function isHeading(line: string): boolean {
  const trimmed = line.trim();
  if (trimmed.length === 0 || trimmed.length > 100) return false;
  if (/^#{1,6}\s+/.test(trimmed)) return true;
  if (/^chapter\s+\d+/i.test(trimmed)) return true;
  if (/^part\s+\d+/i.test(trimmed)) return true;
  if (trimmed.length >= 5 && /^[A-Z0-9\s\-:,.!?']+$/.test(trimmed) && /[A-Z]/.test(trimmed) && !/^[0-9\s]+$/.test(trimmed)) return true;
  return false;
}

// ===== HTML body building =====

/** Build the cover page HTML. */
export function buildCoverPage(opts: Azw3Options): string {
  return `<html><head><title>${escapeHtml(opts.title)}</title></head>
<body>
<h1 style="text-align:center;font-size:3em;margin-top:4em;">${escapeHtml(opts.title)}</h1>
<p style="text-align:center;font-size:1.5em;color:#666;">${escapeHtml(opts.author)}</p>
<p style="text-align:center;font-size:1em;color:#999;margin-top:2em;">${escapeHtml(opts.coverSubtitle)}</p>
</body></html>`;
}

/** Build the body HTML from PDF page texts. */
export function buildHtmlBody(pageTexts: string[], opts: Azw3Options): string {
  const parts: string[] = [];
  if (opts.chapterMode === "single") {
    const allText = pageTexts.join("\n");
    parts.push(buildParagraphs(allText));
    return parts.join("\n");
  }
  if (opts.chapterMode === "heading") {
    let currentTitle = "Introduction";
    let currentParas: string[] = [];
    const flush = () => {
      if (currentParas.length === 0) return;
      parts.push(`<h1>${escapeHtml(currentTitle)}</h1>`);
      parts.push(currentParas.map((p) => `<p>${escapeHtml(p)}</p>`).join("\n"));
      parts.push("<mbp:pagebreak/>");
      currentParas = [];
    };
    for (const pageText of pageTexts) {
      for (const line of pageText.split("\n")) {
        const trimmed = line.trim();
        if (trimmed === "") continue;
        if (isHeading(trimmed)) {
          flush();
          currentTitle = trimmed.replace(/^#{1,6}\s+/, "");
        } else {
          currentParas.push(trimmed);
        }
      }
    }
    flush();
    return parts.join("\n");
  }
  // page mode
  for (let i = 0; i < pageTexts.length; i++) {
    const text = pageTexts[i] ?? "";
    if (text.trim() === "") continue;
    const firstLine = text.split("\n").map((l) => l.trim()).find((l) => l !== "") ?? `Page ${i + 1}`;
    const title = firstLine.length <= 80 ? firstLine : `Page ${i + 1}`;
    parts.push(`<h1>${escapeHtml(title)}</h1>`);
    parts.push(buildParagraphs(text));
    parts.push("<mbp:pagebreak/>");
  }
  return parts.join("\n");
}

/** Convert plain text into HTML paragraphs (one <p> per non-empty line). */
export function buildParagraphs(text: string): string {
  return text
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l !== "")
    .map((l) => `<p>${escapeHtml(l)}</p>`)
    .join("\n");
}

// ===== Text record splitting =====

class Cp1252Encoder {
  encode(str: string): Uint8Array {
    const out = new Uint8Array(str.length);
    for (let i = 0; i < str.length; i++) out[i] = str.charCodeAt(i) & 0xff;
    return out;
  }
}

export function splitTextRecords(html: string, encoding: Azw3Encoding): Uint8Array[] {
  const encoder = encoding === "utf-8" ? new TextEncoder() : new Cp1252Encoder();
  const allBytes = encoder.encode(html);
  const records: Uint8Array[] = [];
  for (let i = 0; i < allBytes.length; i += TEXT_RECORD_SIZE) {
    const end = Math.min(i + TEXT_RECORD_SIZE, allBytes.length);
    records.push(allBytes.subarray(i, end));
  }
  if (records.length === 0) records.push(new Uint8Array(0));
  return records;
}

// ===== PalmDB header =====

export function generatePalmDbHeader(name: string, recordCount: number): Uint8Array {
  const bytes = new Uint8Array(PALMDB_HEADER_SIZE);
  writePaddedAscii(bytes, 0, name, 32);
  writeU16BE(bytes, 32, 0);
  writeU16BE(bytes, 34, 0);
  const now = Math.floor(Date.now() / 1000);
  const palmTime = now + 2082844800;
  writeU32BE(bytes, 36, palmTime);
  writeU32BE(bytes, 40, palmTime);
  writeU32BE(bytes, 44, palmTime);
  writeU32BE(bytes, 48, 0);
  writeU32BE(bytes, 52, 0);
  writeU32BE(bytes, 56, 0);
  writeAscii(bytes, 60, "BOOK");
  writeAscii(bytes, 64, "MOBI");
  writeU32BE(bytes, 68, recordCount + 1);
  writeU32BE(bytes, 72, 0);
  writeU16BE(bytes, 76, recordCount);
  return bytes;
}

// ===== Record info table =====

export function generateRecordInfoTable(recordOffsets: Array<{ offset: number; uniqueId: number }>): Uint8Array {
  const bytes = new Uint8Array(recordOffsets.length * RECORD_INFO_SIZE);
  for (let i = 0; i < recordOffsets.length; i++) {
    const info = recordOffsets[i]!;
    const baseOffset = i * RECORD_INFO_SIZE;
    writeU32BE(bytes, baseOffset, info.offset);
    bytes[baseOffset + 4] = 0;
    bytes[baseOffset + 5] = (info.uniqueId >>> 16) & 0xff;
    bytes[baseOffset + 6] = (info.uniqueId >>> 8) & 0xff;
    bytes[baseOffset + 7] = info.uniqueId & 0xff;
  }
  return bytes;
}

// ===== PalmDOC header =====

export function generatePalmDocHeader(textLength: number, textRecordCount: number): Uint8Array {
  const bytes = new Uint8Array(PALMDOC_HEADER_SIZE);
  writeU16BE(bytes, 0, 1); // compression: 1 = none
  writeU16BE(bytes, 2, 0);
  writeU32BE(bytes, 4, textLength);
  writeU16BE(bytes, 8, textRecordCount);
  writeU16BE(bytes, 10, TEXT_RECORD_SIZE);
  writeU16BE(bytes, 12, 0); // encryption: 0 = none
  return bytes;
}

// ===== MOBI header (with KF8 marker) =====

export function generateMobiHeader(opts: Azw3Options, textLength: number, textRecordCount: number): Uint8Array {
  const bytes = new Uint8Array(MOBI_HEADER_SIZE);
  writeAscii(bytes, 0, "MOBI");
  writeU32BE(bytes, 4, MOBI_HEADER_SIZE);
  writeU32BE(bytes, 8, 6); // MOBI type: 6 = KF8
  writeU32BE(bytes, 12, opts.encoding === "utf-8" ? 65001 : 1252);
  writeU32BE(bytes, 16, Math.floor(Math.random() * 0xffffffff));
  writeU32BE(bytes, 20, 8); // File version: 8 (KF8)
  writeU32BE(bytes, 24, 0xffffffff);
  writeU32BE(bytes, 28, 0xffffffff);
  writeU32BE(bytes, 32, 0xffffffff);
  writeU32BE(bytes, 36, textRecordCount + 2); // first image record
  writeU32BE(bytes, 40, 0);
  return bytes;
}

// ===== EXTH header =====

export function generateExthHeader(opts: Azw3Options): Uint8Array {
  const records: Array<{ type: number; data: Uint8Array }> = [];
  const enc = new TextEncoder();
  records.push({ type: 100, data: enc.encode(opts.author) });
  records.push({ type: 503, data: enc.encode(opts.title) });
  records.push({ type: 524, data: enc.encode(opts.language) });
  // KF8-specific: type 117 = cover image record index (we set to 0 — no cover image)
  const coverBytes = new Uint8Array(4);
  writeU32BE(coverBytes, 0, 0);
  records.push({ type: 117, data: coverBytes });
  const recordsSize = records.reduce((s, r) => s + 8 + r.data.length, 0);
  const headerSize = 12 + recordsSize;
  const bytes = new Uint8Array(headerSize);
  writeAscii(bytes, 0, "EXTH");
  writeU32BE(bytes, 4, headerSize);
  writeU32BE(bytes, 8, records.length);
  let offset = 12;
  for (const r of records) {
    writeU32BE(bytes, offset, r.type);
    writeU32BE(bytes, offset + 4, 8 + r.data.length);
    bytes.set(r.data, offset + 8);
    offset += 8 + r.data.length;
  }
  return bytes;
}

// ===== KF8 boundary record =====

/** Generate the KF8 boundary 'BOUNDARY' marker record (8 bytes). */
export function generateKf8BoundaryRecord(): Uint8Array {
  const bytes = new Uint8Array(8);
  writeAscii(bytes, 0, KF8_BOUNDARY_MARKER);
  return bytes;
}

// ===== Record 0 assembly =====

export function assembleRecord0(opts: Azw3Options, textLength: number, textRecordCount: number): Uint8Array {
  const palmDoc = generatePalmDocHeader(textLength, textRecordCount);
  const mobi = generateMobiHeader(opts, textLength, textRecordCount);
  const exth = generateExthHeader(opts);
  const out = new Uint8Array(palmDoc.length + mobi.length + exth.length);
  out.set(palmDoc, 0);
  out.set(mobi, palmDoc.length);
  out.set(exth, palmDoc.length + mobi.length);
  return out;
}

// ===== Top-level AZW3 assembly =====

export function assembleAzw3(pageTexts: string[], opts: Azw3Options): Uint8Array {
  const coverHtml = buildCoverPage(opts);
  const bodyHtml = buildHtmlBody(pageTexts, opts);
  // Combine cover + body
  const fullHtml = coverHtml + "\n<mbp:pagebreak/>\n" + bodyHtml;
  const textRecords = splitTextRecords(fullHtml, opts.encoding);
  const encoder = opts.encoding === "utf-8" ? new TextEncoder() : new Cp1252Encoder();
  const textLength = encoder.encode(fullHtml).length;
  const record0 = assembleRecord0(opts, textLength, textRecords.length);
  const boundaryRec = generateKf8BoundaryRecord();
  // All records: record0 + text records + boundary
  const allRecords = [record0, ...textRecords, boundaryRec];
  const recordCount = allRecords.length;
  const headerTotal = PALMDB_HEADER_SIZE + recordCount * RECORD_INFO_SIZE + 2;
  const recordOffsets: Array<{ offset: number; uniqueId: number }> = [];
  let offset = headerTotal;
  for (let i = 0; i < allRecords.length; i++) {
    recordOffsets.push({ offset, uniqueId: i });
    offset += allRecords[i]!.length;
  }
  const totalSize = headerTotal + allRecords.reduce((s, r) => s + r.length, 0);
  const out = new Uint8Array(totalSize);
  const palmDbHeader = generatePalmDbHeader(opts.title, recordCount);
  out.set(palmDbHeader, 0);
  const recordInfo = generateRecordInfoTable(recordOffsets);
  out.set(recordInfo, PALMDB_HEADER_SIZE);
  let pos = headerTotal;
  for (const rec of allRecords) {
    out.set(rec, pos);
    pos += rec.length;
  }
  return out;
}

// ===== Top-level conversion =====

export async function convertPdfToAzw3(
  pdfBytes: Uint8Array,
  opts: Azw3Options = DEFAULT_OPTIONS,
  outputFileName: string = "converted.azw3",
): Promise<ToolResult<Azw3Result>> {
  const textOptions: TextOptions = {
    pageRange: opts.pageRange,
    lineSeparator: "\n",
    pageSeparator: "",
    trimLines: true,
    removeEmptyLines: false,
    lineNumbers: false,
    addBom: false,
  };
  const textResult = await extractPdfText(pdfBytes, textOptions);
  if (!textResult.ok) {
    return { ok: false, error: textResult.error };
  }
  const pageTexts = textResult.output.pages.map((p) => p.text);
  if (pageTexts.every((p) => p.trim() === "")) {
    return { ok: false, error: "No text content found in the PDF." };
  }
  const azw3Bytes = assembleAzw3(pageTexts, opts);
  const coverHtml = buildCoverPage(opts);
  const bodyHtml = buildHtmlBody(pageTexts, opts);
  const fullHtml = coverHtml + "\n<mbp:pagebreak/>\n" + bodyHtml;
  const encoder = opts.encoding === "utf-8" ? new TextEncoder() : new Cp1252Encoder();
  const textLength = encoder.encode(fullHtml).length;
  const textRecordCount = Math.max(1, Math.ceil(textLength / TEXT_RECORD_SIZE));
  const blob = new Blob([azw3Bytes as BlobPart], { type: "application/x-mobipocket-ebook" });
  return {
    ok: true,
    output: {
      blob,
      fileName: outputFileName,
      recordCount: textRecordCount + 2, // +1 for record 0, +1 for boundary
      textRecordCount,
      wordCount: textResult.output.totalWordCount,
      charCount: textResult.output.totalCharCount,
      pageCount: textResult.output.pageCount,
      azw3Bytes: azw3Bytes.length,
    },
  };
}

// ===== Utilities =====

export { formatBytes };

// ===== History =====

const HISTORY_KEY = "unqtools-pdf-to-azw3-history";
const MAX_HISTORY = 10;

export interface HistoryEntry {
  fileName: string;
  pdfBytes: number;
  azw3Bytes: number;
  recordCount: number;
  wordCount: number;
  convertedAt: string;
}

export function loadHistory(): HistoryEntry[] {
  if (typeof localStorage === "undefined") return [];
  try {
    const raw = localStorage.getItem(HISTORY_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.slice(0, MAX_HISTORY) : [];
  } catch { return []; }
}

export function saveToHistory(entry: HistoryEntry): HistoryEntry[] {
  if (typeof localStorage === "undefined") return [];
  const updated = [entry, ...loadHistory()].slice(0, MAX_HISTORY);
  try { localStorage.setItem(HISTORY_KEY, JSON.stringify(updated)); } catch { /* ignore */ }
  return updated;
}

export function clearHistory(): void {
  if (typeof localStorage === "undefined") return;
  try { localStorage.removeItem(HISTORY_KEY); } catch { /* ignore */ }
}

// ===== Shareable URL =====

export function buildShareUrl(opts: Azw3Options): string {
  if (typeof window === "undefined") return "";
  const params = new URLSearchParams();
  if (opts.pageRange) params.set("pages", opts.pageRange);
  params.set("mode", opts.chapterMode);
  params.set("enc", opts.encoding);
  if (opts.title && opts.title !== DEFAULT_OPTIONS.title) params.set("title", opts.title);
  if (opts.author && opts.author !== DEFAULT_OPTIONS.author) params.set("author", opts.author);
  params.set("lang", opts.language);
  return `${window.location.origin}${window.location.pathname}#${params.toString()}`;
}

export function parseShareUrl(hash: string): Partial<Azw3Options> | null {
  if (!hash || !hash.startsWith("#")) return null;
  const params = new URLSearchParams(hash.slice(1));
  if (!params.has("mode") && !params.has("pages")) return null;
  const mode = (params.get("mode") ?? "page") as Azw3ChapterMode;
  const validModes: Azw3ChapterMode[] = ["page", "heading", "single"];
  const enc = (params.get("enc") ?? "utf-8") as Azw3Encoding;
  const validEncs: Azw3Encoding[] = ["utf-8", "cp1252"];
  return {
    pageRange: params.get("pages") ?? "",
    chapterMode: validModes.includes(mode) ? mode : "page",
    encoding: validEncs.includes(enc) ? enc : "utf-8",
    title: params.get("title") ?? "",
    author: params.get("author") ?? "",
    language: params.get("lang") ?? "en",
  };
}
